// Language quiz bank. Each entry has:
//   lang      - canonical language name (shown after guess)
//   aliases   - other acceptable names the user might type
//   tag       - BCP-47 lang tag for font rendering hints
//   variants  - array of {phrase, translation, tip, highlights}
//     phrase      - sentence/phrase in the language's native script
//     translation - English translation
//     tip         - how to quickly tell this language apart
//     highlights  - exact substrings in the phrase to wrap as <mark class="tell">
const QUESTIONS = [
  {
    lang: "Spanish",
    aliases: ["Español", "Castellano", "Castilian"],
    tag: "es",
    variants: [
      { phrase: "¿Dónde está la biblioteca más cercana?", translation: "Where is the nearest library?", tip: "The inverted ¿ opening a question (paired with a normal ?) is unique to Spanish.", highlights: ["¿", "?"] },
      { phrase: "¡Qué día más bonito hace hoy!", translation: "What a beautiful day it is today!", tip: "Inverted ¡ opening an exclamation is a Spanish signature.", highlights: ["¡", "!"] },
      { phrase: "El niño pequeño sueña con las montañas.", translation: "The little boy dreams of the mountains.", tip: "The letter ñ is almost exclusively Spanish (and a few neighbours that borrowed it).", highlights: ["ñ", "ñ", "ñ"] },
      { phrase: "La educación y la tradición construyen la nación.", translation: "Education and tradition build the nation.", tip: "The -ción suffix (cognate of English -tion) is everywhere in Spanish.", highlights: ["ción", "ción", "ción"] },
      { phrase: "El café está un poco frío todavía.", translation: "The coffee is still a bit cold.", tip: "Acute accents only on vowels (á é í ó ú) marking stress — no circumflex, no grave.", highlights: ["é", "á", "í", "í"] },
      { phrase: "La lluvia cae sobre el caballo amarillo.", translation: "The rain falls on the yellow horse.", tip: "The 'll' digraph (pronounced like 'y' or 'j') is a Spanish hallmark.", highlights: ["ll", "ll", "ll"] },
      { phrase: "El perro corre por la tierra mojada.", translation: "The dog runs across the wet earth.", tip: "Double 'rr' marks a trilled r — Spanish uses it between vowels.", highlights: ["rr", "rr", "rr"] },
      { phrase: "Verdaderamente estaba completamente perdido.", translation: "He was truly, completely lost.", tip: "Adverbs end in -mente, the Spanish equivalent of English -ly.", highlights: ["mente", "mente"] },
    ],
  },
  {
    lang: "French",
    aliases: ["Français"],
    tag: "fr",
    variants: [
      { phrase: "Je ne sais pas ce que tu veux dire.", translation: "I don't know what you mean.", tip: "The 'ne … pas' sandwich wrapping the verb is pure French negation.", highlights: ["ne", "pas"] },
      { phrase: "Ça va, merci, et toi ?", translation: "I'm fine, thanks — and you?", tip: "The cedilla ç (softening c to s before a/o/u) is French (and Portuguese/Catalan).", highlights: ["Ç"] },
      { phrase: "L'hôtel est près de la forêt.", translation: "The hotel is near the forest.", tip: "The circumflex (â ê î ô û) often marks a lost historical 's' — a French fingerprint.", highlights: ["ô", "ê"] },
      { phrase: "J'aime l'école et l'été à Paris.", translation: "I love school and summer in Paris.", tip: "Apostrophe elisions (l', d', j', qu') are constant in French.", highlights: ["J'", "l'", "l'"] },
      { phrase: "Très bientôt, après la pièce.", translation: "Very soon, after the play.", tip: "The grave accent è (and à, ù) marks open vowels — French uses it often.", highlights: ["è", "è"] },
      { phrase: "Voici les nouveaux chevaux du château.", translation: "Here are the new horses of the castle.", tip: "Plurals in -eaux and -aux are a distinctive French spelling.", highlights: ["eaux", "aux", "eau"] },
      { phrase: "Qu'est-ce que tu fais maintenant ?", translation: "What are you doing right now?", tip: "'Qu'est-ce que' and the space before '?' are French conventions.", highlights: ["Qu'", " ?"] },
      { phrase: "Les oiseaux chantent sous le ciel bleu.", translation: "The birds sing under the blue sky.", tip: "Vowel clusters like 'eau', 'oi' and 'eu' produce single sounds — very French.", highlights: ["eau", "oi", "eu", "eu"] },
    ],
  },
  {
    lang: "German",
    aliases: ["Deutsch"],
    tag: "de",
    variants: [
      { phrase: "Die Straße ist sehr groß.", translation: "The street is very big.", tip: "The ß (eszett) is used only in German (and Swiss German rarely) — an instant tell.", highlights: ["ß", "ß"] },
      { phrase: "Mein Bruder trägt einen grünen Hut.", translation: "My brother is wearing a green hat.", tip: "Umlauts ä, ö, ü are classic German (and a few neighbours).", highlights: ["ä", "ü"] },
      { phrase: "Der Hund schläft auf dem Sofa im Wohnzimmer.", translation: "The dog is sleeping on the sofa in the living room.", tip: "Every noun is Capitalised mid-sentence — a unique orthographic habit.", highlights: ["Hund", "Sofa", "Wohnzimmer"] },
      { phrase: "Die Geschwindigkeitsbegrenzung gilt auch nachts.", translation: "The speed limit applies at night too.", tip: "Long compound nouns (one word stitched from many) are a German specialty.", highlights: ["Geschwindigkeitsbegrenzung"] },
      { phrase: "Ich kann dich nicht verstehen.", translation: "I can't understand you.", tip: "The 'ch' digraph after vowels (ich, nicht, auch) gives German its throaty sound.", highlights: ["ch", "ch"] },
      { phrase: "Seine Freundschaft bedeutet mir viel.", translation: "His friendship means a lot to me.", tip: "The -schaft suffix (like English -ship) is a German giveaway.", highlights: ["schaft"] },
      { phrase: "Die Meinung der Bevölkerung ist wichtig.", translation: "The opinion of the population is important.", tip: "The -ung suffix (forming nouns from verbs) is everywhere in German.", highlights: ["ung", "ung"] },
      { phrase: "Die Schönheit und Wahrheit der Freiheit.", translation: "The beauty and truth of freedom.", tip: "The -heit / -keit noun suffix is a hallmark of German.", highlights: ["heit", "heit", "heit"] },
    ],
  },
  {
    lang: "Italian",
    aliases: ["Italiano"],
    tag: "it",
    variants: [
      { phrase: "La pizza è davvero buonissima stasera.", translation: "The pizza is really excellent tonight.", tip: "The superlative -issimo/-issima is very Italian.", highlights: ["issima"] },
      { phrase: "Il cane corre velocemente nel prato.", translation: "The dog runs quickly across the meadow.", tip: "Almost every Italian word ends in a vowel.", highlights: ["e", "e", "e", "o", "o"] },
      { phrase: "La ragazza mangia la pizza con la mozzarella.", translation: "The girl is eating pizza with mozzarella.", tip: "Doubled consonants (zz, ll, tt, ss) are very common in Italian.", highlights: ["zz", "zz", "zz"] },
      { phrase: "Gli amici sono già nel giardino.", translation: "The friends are already in the garden.", tip: "The 'gli' digraph (a palatal 'lyi' sound) is distinctively Italian.", highlights: ["Gli", "gi"] },
      { phrase: "Il bagno è vicino alla cucina.", translation: "The bathroom is near the kitchen.", tip: "The 'gn' digraph (like Spanish ñ) is an Italian signature.", highlights: ["gn", "ci"] },
      { phrase: "Caffè, tè, e perché no, un gelato.", translation: "Coffee, tea, and why not, an ice cream.", tip: "The grave accent è / ò / à sits on final vowels to mark stress — very Italian.", highlights: ["è", "è", "é"] },
      { phrase: "Non c'è niente da fare qui.", translation: "There's nothing to do here.", tip: "The phrase 'c'è' (there is) and apostrophe elisions are Italian staples.", highlights: ["c'è"] },
      { phrase: "Questo libro è più interessante degli altri.", translation: "This book is more interesting than the others.", tip: "Words like 'più', 'degli' and vowel-heavy forms mark Italian.", highlights: ["ù", "gli"] },
    ],
  },
  {
    lang: "Portuguese",
    aliases: ["Português"],
    tag: "pt",
    variants: [
      { phrase: "Não sei o que você está dizendo.", translation: "I don't know what you're saying.", tip: "The nasal 'ão' is the Portuguese fingerprint — no other European language uses it.", highlights: ["ão"] },
      { phrase: "O coração da canção é uma emoção.", translation: "The heart of the song is an emotion.", tip: "Words ending in -ção are everywhere (cognate of Spanish -ción, English -tion).", highlights: ["ção", "ção", "ção"] },
      { phrase: "As irmãs são muito simpáticas.", translation: "The sisters are very kind.", tip: "The nasal tilde on ã (and its plural ãs) marks Portuguese.", highlights: ["ã", "ão"] },
      { phrase: "As lições do avô são limões amargos.", translation: "Grandfather's lessons are bitter lemons.", tip: "The tilde on õ appears only in Portuguese among European languages.", highlights: ["õ", "ô"] },
      { phrase: "A informação está disponível em português.", translation: "The information is available in Portuguese.", tip: "The cedilha ç sits before a/o/u, just like in French.", highlights: ["ç", "ê"] },
      { phrase: "O filho pequeno olha para a montanha.", translation: "The small son looks at the mountain.", tip: "The 'lh' and 'nh' digraphs (≈ Italian gl/gn) are Portuguese signatures.", highlights: ["lh", "nh"] },
      { phrase: "Até já, meu amigo querido.", translation: "See you soon, my dear friend.", tip: "Acutes on vowels (á é í ó ú) mark open stressed vowels in Portuguese.", highlights: ["é", "á"] },
      { phrase: "Você é um ótimo amigo.", translation: "You are a great friend.", tip: "'Você' (with ê) + acute on ótimo distinguish Portuguese from Spanish.", highlights: ["Você", "ê", "ó"] },
    ],
  },
  {
    lang: "Dutch",
    aliases: ["Nederlands", "Flemish"],
    tag: "nl",
    variants: [
      { phrase: "Mijn vriendin spreekt altijd Nederlands.", translation: "My girlfriend always speaks Dutch.", tip: "The 'ij' digraph is treated like one letter — unmistakably Dutch.", highlights: ["ij", "ij"] },
      { phrase: "De maan staat hoog boven de boom.", translation: "The moon stands high above the tree.", tip: "Doubled vowels (aa, ee, oo, uu) mark long sounds — a Dutch specialty.", highlights: ["aa", "oo"] },
      { phrase: "De schilder schildert een mooi schilderij.", translation: "The painter paints a beautiful painting.", tip: "The 'sch' cluster (especially at word starts and -schap endings) is classic Dutch.", highlights: ["sch", "sch", "sch"] },
      { phrase: "Dit huis heeft een groene deur.", translation: "This house has a green door.", tip: "The 'ui' diphthong and doubled 'ee' together point to Dutch.", highlights: ["ui", "oe", "ee"] },
      { phrase: "Goedemorgen, hoe gaat het met je?", translation: "Good morning, how are you?", tip: "The 'oe' vowel (like English 'oo') and 'g' sounds are Dutch signals.", highlights: ["oe", "oe"] },
      { phrase: "De vrijheid en de gezelligheid van het dorp.", translation: "The freedom and cosiness of the village.", tip: "The suffix -heid (like German -heit / English -hood) is Dutch.", highlights: ["heid", "heid"] },
      { phrase: "Van het kasteel naar het bos.", translation: "From the castle to the forest.", tip: "Tiny words like 'van', 'het', 'de' pack most Dutch sentences.", highlights: ["Van", "het", "het"] },
      { phrase: "Alsjeblieft, neem een koekje.", translation: "Please, take a cookie.", tip: "Diminutive -je / -tje endings are a Dutch staple.", highlights: ["je", "je"] },
    ],
  },
  {
    lang: "Swedish",
    aliases: ["Svenska"],
    tag: "sv",
    variants: [
      { phrase: "Jag åker tåg till Göteborg imorgon.", translation: "I'm taking the train to Gothenburg tomorrow.", tip: "The ring-a 'å' and dieresis ä/ö together (never æ/ø) = Swedish.", highlights: ["å", "å", "ö"] },
      { phrase: "Jag och min bror är hemma idag.", translation: "My brother and I are home today.", tip: "Tiny function words 'jag', 'och', 'är' stud every Swedish sentence.", highlights: ["Jag", "och", "är"] },
      { phrase: "Skinkan och skeppet är på bordet.", translation: "The ham and the ship are on the table.", tip: "The 'sk' before front vowels turns into a shh/hw sound — a Swedish tell.", highlights: ["Sk", "sk"] },
      { phrase: "Flickan tjänar pengar på kaféet.", translation: "The girl earns money at the café.", tip: "'tj' (as in 'tjugo') is a soft 'sh/hj' sound found in Swedish.", highlights: ["tj", "é"] },
      { phrase: "Huset är nära sjön i skogen.", translation: "The house is near the lake in the forest.", tip: "The definite article is a suffix (-et/-en/-n) rather than a separate word.", highlights: ["et", "en", "en", "en"] },
      { phrase: "Vädret är väldigt vackert idag.", translation: "The weather is very beautiful today.", tip: "Lots of 'v' words and the ä vowel mark Swedish.", highlights: ["ä", "ä", "ä"] },
      { phrase: "Snön faller över fjället.", translation: "The snow falls over the mountain.", tip: "Words like 'snö', 'över', 'fjäll' combine ö + ä — Swedish, not Norwegian/Danish.", highlights: ["ö", "ö", "ä"] },
      { phrase: "Hon tycker om att åka skidor.", translation: "She likes to go skiing.", tip: "'tycker om' (like) and 'åka' with å are Swedish tells.", highlights: ["å", "å"] },
    ],
  },
  {
    lang: "Norwegian",
    aliases: ["Norsk", "Bokmål", "Nynorsk"],
    tag: "no",
    variants: [
      { phrase: "Jeg snakker bare litt norsk.", translation: "I only speak a little Norwegian.", tip: "'snakker' (not Danish 'taler') and 'Jeg' lean Norwegian.", highlights: ["snakker"] },
      { phrase: "Været er ganske kjølig i dag.", translation: "The weather is quite cool today.", tip: "The letter 'æ' appears in Norwegian, Danish and Icelandic (but not Swedish).", highlights: ["æ", "ø"] },
      { phrase: "Hun bor på en øy nær kysten.", translation: "She lives on an island near the coast.", tip: "The slashed 'ø' is Norwegian/Danish (Swedish uses ö).", highlights: ["ø", "å"] },
      { phrase: "Jeg har ikke tid til det nå.", translation: "I don't have time for that now.", tip: "'ikke' (not) and 'jeg' are Norwegian workhorses.", highlights: ["ikke", "Jeg", "å"] },
      { phrase: "Hva heter du og hvor bor du?", translation: "What's your name and where do you live?", tip: "'Hv-' question words (hva, hvor, hvem) are a Scandinavian-but-distinctly-Norwegian/Danish feature.", highlights: ["Hv", "hv"] },
      { phrase: "Boken er på bordet i stua.", translation: "The book is on the table in the living room.", tip: "Definite article as a suffix: bok → boken, bord → bordet.", highlights: ["en", "et", "a"] },
      { phrase: "Skjerfet og kjolen er rene.", translation: "The scarf and the dress are clean.", tip: "The 'skj' and 'kj' clusters stand for the Norwegian /ç/ and /ʂ/ sounds.", highlights: ["Skj", "kj"] },
      { phrase: "Jeg liker å gå tur i skogen.", translation: "I like to go for a walk in the forest.", tip: "'å' before infinitives marks them ('å gå' = to go) — typical Norwegian.", highlights: ["å", "å"] },
    ],
  },
  {
    lang: "Danish",
    aliases: ["Dansk"],
    tag: "da",
    variants: [
      { phrase: "Jeg taler kun lidt dansk, desværre.", translation: "I only speak a little Danish, unfortunately.", tip: "'taler' (not Norwegian 'snakker') and 'desværre' with æ lean Danish.", highlights: ["taler", "æ"] },
      { phrase: "Øen ligger tæt på kysten.", translation: "The island lies close to the coast.", tip: "'ø' + 'æ' in the same sentence is typical Danish/Norwegian spelling.", highlights: ["Ø", "æ"] },
      { phrase: "Jeg kan ikke finde mine nøgler.", translation: "I can't find my keys.", tip: "'ikke' + 'nøgle' with a soft 'g' and silent endings are Danish staples.", highlights: ["ikke", "ø"] },
      { phrase: "Hvad laver du i morgen?", translation: "What are you doing tomorrow?", tip: "'Hv-' question words appear in Danish/Norwegian but not Swedish.", highlights: ["Hv"] },
      { phrase: "Huset ligger på hjørnet af gaden.", translation: "The house is on the corner of the street.", tip: "Suffix articles -et / -en are Danish (bag 'house' → huset).", highlights: ["et", "et", "en"] },
      { phrase: "Vi skal købe rødgrød med fløde.", translation: "We're going to buy red berry porridge with cream.", tip: "'rødgrød med fløde' is the famous Danish shibboleth full of ø.", highlights: ["ø", "ø", "ø"] },
      { phrase: "Min søster hedder Astrid.", translation: "My sister is called Astrid.", tip: "'hedder' (is called) and ø in 'søster' mark Danish.", highlights: ["hedder", "ø"] },
      { phrase: "Det er en lille, hyggelig café.", translation: "It's a little, cosy café.", tip: "'hyggelig' (cosy) is a famously Danish word; double vowels less common than Swedish.", highlights: ["hyggelig"] },
    ],
  },
  {
    lang: "Finnish",
    aliases: ["Suomi"],
    tag: "fi",
    variants: [
      { phrase: "Hän ei puhu suomea hyvin.", translation: "He/she doesn't speak Finnish well.", tip: "The ä and ö (never å) plus no articles mark Finnish.", highlights: ["ä"] },
      { phrase: "Yöllä kuu loistaa pään päällä.", translation: "At night the moon shines overhead.", tip: "Long vowels written as doubled letters (yy, uu, ää) are very Finnish.", highlights: ["Yö", "ää", "ää"] },
      { phrase: "Tyttö oppii puhumaan suomea mökissä.", translation: "The girl learns to speak Finnish at the cottage.", tip: "Doubled consonants (tt, pp, kk) contrast with single ones — Finnish phonology.", highlights: ["tt", "pp"] },
      { phrase: "Hän on kaunis ja iloinen.", translation: "He/she is beautiful and happy.", tip: "Finnish has no grammatical gender — 'hän' covers he AND she.", highlights: ["Hän"] },
      { phrase: "Lentokoneessa on paljon matkustajia.", translation: "There are many passengers on the plane.", tip: "Case endings stack onto words — 'lentokone + ssa' (in the plane) is typical Finnish.", highlights: ["ssa", "ia"] },
      { phrase: "Ystävällinen opettaja auttaa oppilaita.", translation: "A kind teacher helps the students.", tip: "The -inen adjective suffix is Finnish (and Estonian).", highlights: ["inen", "ita"] },
      { phrase: "Tuletko kotiin tänään?", translation: "Are you coming home today?", tip: "Questions are formed with the suffix -ko/-kö on the verb.", highlights: ["ko", "ää"] },
      { phrase: "Metsässä kasvaa monta puuta.", translation: "Many trees grow in the forest.", tip: "Inessive case -ssa/-ssä = 'in' — stacks directly onto the noun.", highlights: ["ssä", "uu"] },
    ],
  },
  {
    lang: "Icelandic",
    aliases: ["Íslenska"],
    tag: "is",
    variants: [
      { phrase: "Ég tala smá íslensku.", translation: "I speak a little Icelandic.", tip: "Acute-accent vowels (á é í ó ú ý) mark long vowels in Icelandic.", highlights: ["É", "í"] },
      { phrase: "Það er kalt í dag.", translation: "It is cold today.", tip: "The letter þ (thorn, capitalised Þ) is found essentially only in Icelandic.", highlights: ["Þ"] },
      { phrase: "Góðan daginn, vinur minn.", translation: "Good morning, my friend.", tip: "The letter ð (eth) survives in Icelandic (and Faroese) only.", highlights: ["ð"] },
      { phrase: "Dýrið sýnir nýja hegðun.", translation: "The animal shows new behaviour.", tip: "The vowel 'ý' (y with acute) is an Icelandic fingerprint, alongside ð.", highlights: ["ý", "ý", "ý", "ð"] },
      { phrase: "Bærinn er lítill og fallegur.", translation: "The town is small and beautiful.", tip: "'æ' in Icelandic is a diphthong (roughly 'eye') — paired with 'ur' endings.", highlights: ["æ", "ur", "ur"] },
      { phrase: "Fjöllin eru há og hvít.", translation: "The mountains are tall and white.", tip: "'ö' + 'á' + 'í' all in one sentence is a very Icelandic profile.", highlights: ["ö", "á", "í"] },
      { phrase: "Sonur minn heitir Sigurðsson.", translation: "My son is called Sigurðsson.", tip: "Patronymic surnames end in -son (male) / -dóttir (female) — Icelandic tradition.", highlights: ["son", "son"] },
      { phrase: "Strætisvagninn kemur klukkan þrjú.", translation: "The bus comes at three o'clock.", tip: "'þ' plus the archaic-looking 'strætisvagninn' are Icelandic giveaways.", highlights: ["þ", "æ"] },
    ],
  },
  {
    lang: "Polish",
    aliases: ["Polski"],
    tag: "pl",
    variants: [
      { phrase: "Nie rozumiem, co mówisz do mnie.", translation: "I don't understand what you're saying to me.", tip: "The acute ó (distinct from u) is a Polish hallmark.", highlights: ["ó"] },
      { phrase: "Mała dziewczynka idzie do szkoły.", translation: "The little girl is going to school.", tip: "The slashed 'ł' is the Polish 'w' sound — nearly unique to Polish.", highlights: ["ł", "ł"] },
      { phrase: "Dziękuję bardzo za pomoc.", translation: "Thank you very much for your help.", tip: "Hook-letters ą and ę (nasal vowels) are a Polish signature.", highlights: ["ę"] },
      { phrase: "Szczęśliwego Nowego Roku!", translation: "Happy New Year!", tip: "The 'szcz' cluster is famously Polish.", highlights: ["Szcz", "ęś"] },
      { phrase: "Proszę mówić wolniej.", translation: "Please speak more slowly.", tip: "Ogonek ę and acute ź/ś/ń are Polish spelling tells.", highlights: ["ę", "ó"] },
      { phrase: "Pięć książek leży na stole.", translation: "Five books are lying on the table.", tip: "'ą'/'ę' ogonek vowels sit in nearly every Polish sentence.", highlights: ["ię", "ą"] },
      { phrase: "Czy masz ochotę na herbatę?", translation: "Do you fancy some tea?", tip: "The 'cz' digraph (like English 'ch') is a Slavic Latin-script tell, strongly Polish.", highlights: ["Cz", "ę", "ę"] },
      { phrase: "Rzeka płynie przez miasto.", translation: "The river flows through the city.", tip: "The 'rz' digraph (voiced 'zh') is found in Polish (not in Czech/Slovak).", highlights: ["Rz", "rz"] },
    ],
  },
  {
    lang: "Czech",
    aliases: ["Čeština"],
    tag: "cs",
    variants: [
      { phrase: "Nerozumím, co mi říkáš.", translation: "I don't understand what you're telling me.", tip: "The háček on 'ř' is essentially unique to Czech.", highlights: ["ř", "í", "í"] },
      { phrase: "Dobré ráno, kamaráde!", translation: "Good morning, friend!", tip: "Acute 'á' and 'é' mark long vowels in Czech.", highlights: ["é", "á", "á"] },
      { phrase: "Můj dům je velmi starý.", translation: "My house is very old.", tip: "The ring-u 'ů' marks a long 'oo' sound — only Czech uses it.", highlights: ["ů"] },
      { phrase: "Pět žáků čeká na učitele.", translation: "Five pupils are waiting for the teacher.", tip: "Háček letters č, š, ž pepper Czech text.", highlights: ["ž", "č", "ě"] },
      { phrase: "Ještě jsem nebyl v Praze.", translation: "I haven't been to Prague yet.", tip: "The 'ě' (e with háček) softens the preceding consonant — a Czech marker.", highlights: ["ě", "š"] },
      { phrase: "Čtyři přátelé jdou na pivo.", translation: "Four friends are going for a beer.", tip: "Words can start with 'Č', and 'jdou'/'pivo' are Czech staples.", highlights: ["Č", "ř", "á", "é"] },
      { phrase: "Děkuji vám za pomoc.", translation: "Thank you for your help.", tip: "'Děkuji' (with ě) is the Czech 'thank you'.", highlights: ["Dě", "á"] },
      { phrase: "Praha je krásné město.", translation: "Prague is a beautiful city.", tip: "'město' with the ě-háček and acute á are Czech spellings.", highlights: ["á", "ě"] },
    ],
  },
  {
    lang: "Slovak",
    aliases: ["Slovenčina", "Slovenský"],
    tag: "sk",
    variants: [
      { phrase: "Nerozumiem, čo mi hovoríš.", translation: "I don't understand what you're telling me.", tip: "Looks like Czech, but Slovak never uses 'ř'.", highlights: ["č", "í"] },
      { phrase: "Môj brat býva v Bratislave.", translation: "My brother lives in Bratislava.", tip: "The circumflex 'ô' (pronounced 'wo') is Slovak, not Czech.", highlights: ["ô", "ý"] },
      { phrase: "Máme veľký dom pri lese.", translation: "We have a big house by the forest.", tip: "Soft 'ľ' (l with háček) is a Slovak letter — Czech doesn't use it.", highlights: ["ľ", "á", "ý"] },
      { phrase: "Dnes je krásny slnečný deň.", translation: "Today is a beautiful sunny day.", tip: "Short consonant clusters like 'slnk-' happen because l/r can be syllabic.", highlights: ["á", "č", "ň"] },
      { phrase: "Ďakujem za tvoju pomoc.", translation: "Thank you for your help.", tip: "'Ď' and 'ť' with háček (softened d/t) appear mostly in Slovak.", highlights: ["Ď"] },
      { phrase: "Hovorím trochu po slovensky.", translation: "I speak a little Slovak.", tip: "'hovorím' (I speak) with long-í is a Slovak staple.", highlights: ["í", "í"] },
      { phrase: "Cez víkend pôjdeme do hôr.", translation: "We'll go to the mountains this weekend.", tip: "The circumflex ô appears multiple times in Slovak sentences.", highlights: ["ô", "ô", "í"] },
      { phrase: "Vtáčik spieva v záhrade.", translation: "The little bird sings in the garden.", tip: "Diminutive -ik/-ík and the letter á mark Slovak.", highlights: ["á", "á", "á"] },
    ],
  },
  {
    lang: "Hungarian",
    aliases: ["Magyar"],
    tag: "hu",
    variants: [
      { phrase: "Nem értem, amit éppen mondasz.", translation: "I don't understand what you're saying right now.", tip: "Acute é marks a long e — Hungarian stacks many accents.", highlights: ["é", "é"] },
      { phrase: "A gyönyörű hőlégballon repül.", translation: "The beautiful hot-air balloon is flying.", tip: "The 'double-acute' letters ő and ű exist only in Hungarian.", highlights: ["ő", "ű"] },
      { phrase: "A magyar nyelv nagyon szép.", translation: "The Hungarian language is very beautiful.", tip: "The digraph 'ny' (palatal n, like Spanish ñ) is Hungarian.", highlights: ["ny", "ny"] },
      { phrase: "Megérkeztünk a pályaudvarra.", translation: "We arrived at the railway station.", tip: "Long compound words built by agglutination are a Hungarian specialty.", highlights: ["pályaudvarra"] },
      { phrase: "Egy csésze teát kérek.", translation: "I'd like a cup of tea.", tip: "The digraph 'cs' (like English 'ch') and acute é mark Hungarian.", highlights: ["cs", "é"] },
      { phrase: "Ez a ház gyönyörű és régi.", translation: "This house is beautiful and old.", tip: "'gy' = a soft 'dy' sound — a Hungarian digraph; ű is also Hungarian.", highlights: ["gy", "ű", "é"] },
      { phrase: "A tanárnak írok egy levelet.", translation: "I'm writing a letter to the teacher.", tip: "Case suffixes like -nak/-nek (dative) stack on the noun.", highlights: ["nak", "í"] },
      { phrase: "Zsófia zsebében van egy kulcs.", translation: "Sofia has a key in her pocket.", tip: "'zs' is the Hungarian /ʒ/ sound — like French j.", highlights: ["Zs", "zs"] },
    ],
  },
  {
    lang: "Romanian",
    aliases: ["Română", "Romanian"],
    tag: "ro",
    variants: [
      { phrase: "Nu înțeleg ce îmi spui acum.", translation: "I don't understand what you're telling me now.", tip: "The comma-below letters ș, ț are exclusively Romanian.", highlights: ["ț", "î", "î"] },
      { phrase: "Mâine mergem la mare.", translation: "Tomorrow we're going to the sea.", tip: "The â (circumflex a) is Romanian, distinct from ă.", highlights: ["â"] },
      { phrase: "O să plouă mâine dimineață.", translation: "It's going to rain tomorrow morning.", tip: "The ă (breve a / schwa) is a Romanian vowel.", highlights: ["ă", "ă", "â", "ț"] },
      { phrase: "Copilul este foarte obosit.", translation: "The child is very tired.", tip: "Definite article -l / -ul is attached as a suffix in Romanian.", highlights: ["ul", "e"] },
      { phrase: "Românii vorbesc o limbă romanică.", translation: "Romanians speak a Romance language.", tip: "Romanian is the only Romance language with â/î and ș/ț.", highlights: ["â", "ă"] },
      { phrase: "Îmi place cafeaua fierbinte.", translation: "I like hot coffee.", tip: "Words can start with Î (capital i with circumflex) — distinctly Romanian.", highlights: ["Î"] },
      { phrase: "Mulțumesc pentru ajutorul tău.", translation: "Thank you for your help.", tip: "'Mulțumesc' (thanks) uses ț; -esc verb endings are Romanian.", highlights: ["ț", "ă"] },
      { phrase: "Șapte pisici stau pe stradă.", translation: "Seven cats are on the street.", tip: "'Ș' at the start (with comma-below) is a Romanian signal.", highlights: ["Ș", "ă"] },
    ],
  },
  {
    lang: "Turkish",
    aliases: ["Türkçe"],
    tag: "tr",
    variants: [
      { phrase: "Kızım kahvaltıda çay içiyor.", translation: "My daughter is drinking tea at breakfast.", tip: "The dotless ı (vs. dotted i) is a Turkish distinction — unique to its alphabet.", highlights: ["ı", "ı", "ı", "ç"] },
      { phrase: "Ağaç çok büyüktür.", translation: "The tree is very big.", tip: "The soft-g 'ğ' (silent, lengthening the preceding vowel) is uniquely Turkish.", highlights: ["ğ", "ç", "ü"] },
      { phrase: "Şimdi okula gidiyorum.", translation: "I'm going to school now.", tip: "The progressive suffix -iyor is everywhere in modern Turkish.", highlights: ["Ş", "iyor"] },
      { phrase: "Çok teşekkür ederim.", translation: "Thank you very much.", tip: "The letter 'ç' (like English 'ch') plus 'ş' mark Turkish.", highlights: ["Ç", "ş"] },
      { phrase: "Evlerimizden çok uzaktayız.", translation: "We are very far from our houses.", tip: "Agglutinated endings (plural + possessive + case) stack in one word.", highlights: ["lerimizden", "ç"] },
      { phrase: "Kahvaltıda peynir ve zeytin yerim.", translation: "At breakfast I eat cheese and olives.", tip: "Dotless 'ı' appears where English/other Turkic languages use 'i'.", highlights: ["ı", "ı"] },
      { phrase: "Güneş çok parlak bugün.", translation: "The sun is very bright today.", tip: "Vowel harmony keeps ü/ö with similar vowels; ü + ş = Turkish.", highlights: ["ü", "ş"] },
      { phrase: "İstanbul dünyanın en güzel şehri.", translation: "Istanbul is the most beautiful city in the world.", tip: "Capital İ with a dot (and dotless I) are a Turkish idiosyncrasy.", highlights: ["İ", "ü", "ş"] },
    ],
  },
  {
    lang: "Greek",
    aliases: ["Ελληνικά", "Hellenic"],
    tag: "el",
    variants: [
      { phrase: "Δεν καταλαβαίνω τι λες.", translation: "I don't understand what you're saying.", tip: "Capital letters like Δ (delta) and the Greek script are unmistakable.", highlights: ["Δ"] },
      { phrase: "Ο Ωκεανός είναι πολύ μεγάλος.", translation: "The ocean is very big.", tip: "Ω (omega) and the word Ωκεανός are classic Greek tells.", highlights: ["Ω"] },
      { phrase: "Η φιλοσοφία είναι σημαντική.", translation: "Philosophy is important.", tip: "Letters φ (phi) and ψ (psi) appear only in Greek.", highlights: ["φ"] },
      { phrase: "Καλημέρα, πώς είσαι σήμερα;", translation: "Good morning, how are you today?", tip: "The Greek question mark is ';' (a semicolon).", highlights: [";", "ώ"] },
      { phrase: "Η θάλασσα είναι ήρεμη απόψε.", translation: "The sea is calm tonight.", tip: "The letter θ (theta) and stress accents over vowels mark Greek.", highlights: ["θ", "ή", "ό"] },
      { phrase: "Μιλάω λίγα ελληνικά.", translation: "I speak a little Greek.", tip: "Verb ending -άω and stress accents are Greek staples.", highlights: ["άω", "ά"] },
      { phrase: "Τέσσερις φίλοι πηγαίνουν στο σχολείο.", translation: "Four friends are going to school.", tip: "Final sigma 'ς' appears only at word ends in Greek.", highlights: ["ς", "ς", "ί"] },
      { phrase: "Αγαπώ τα ελληνικά νησιά.", translation: "I love the Greek islands.", tip: "The acute tonos on vowels (ώ, ά, ή) is the Greek stress marker.", highlights: ["ώ", "ά", "ά"] },
    ],
  },
  {
    lang: "Russian",
    aliases: ["Русский"],
    tag: "ru",
    variants: [
      { phrase: "Я плохо говорю по-русски.", translation: "I don't speak Russian well.", tip: "Cyrillic 'Я' (capital) and 'я' (I) are Russian letters.", highlights: ["Я"] },
      { phrase: "Мы любим русскую зиму.", translation: "We love Russian winter.", tip: "The letter ы (a back-vowel) is Cyrillic-Russian.", highlights: ["ы"] },
      { phrase: "Это моя новая квартира.", translation: "This is my new apartment.", tip: "The letter 'э' is used in Russian but not Ukrainian.", highlights: ["Э"] },
      { phrase: "Подъезд находится за углом.", translation: "The entrance is around the corner.", tip: "The hard sign 'ъ' (silent, separating prefixes) is Russian/Bulgarian.", highlights: ["ъ"] },
      { phrase: "Ёлка стоит в углу комнаты.", translation: "The fir tree stands in the corner of the room.", tip: "The letter ё (with dieresis) is Russian — often optional in print.", highlights: ["Ё"] },
      { phrase: "Он хочет читать книгу.", translation: "He wants to read a book.", tip: "Infinitives end in -ть — a Russian verb-ending tell.", highlights: ["ть"] },
      { phrase: "Сегодня очень холодно.", translation: "It's very cold today.", tip: "'Сегодня' and 'очень' are Russian high-frequency words.", highlights: ["Се", "оч"] },
      { phrase: "Спасибо за вашу помощь.", translation: "Thank you for your help.", tip: "'Спасибо' (thanks) and 'щ' (a letter unique to Cyrillic) are Russian tells.", highlights: ["щ"] },
    ],
  },
  {
    lang: "Ukrainian",
    aliases: ["Українська"],
    tag: "uk",
    variants: [
      { phrase: "Мій друг і його сім'я з Києва.", translation: "My friend and his family are from Kyiv.", tip: "Cyrillic with 'і' (Latin-looking i) and apostrophes inside words — Russian has neither.", highlights: ["і", "і", "і", "'"] },
      { phrase: "Мої друзі співають пісню.", translation: "My friends are singing a song.", tip: "The letter 'ї' (i with dieresis) is Ukrainian, not Russian.", highlights: ["ї", "і"] },
      { phrase: "Єдиний вихід — направо.", translation: "The only way out is to the right.", tip: "The letter 'Є' (ye) is Ukrainian, absent from Russian.", highlights: ["Є"] },
      { phrase: "Ґудзик відірвався від пальта.", translation: "The button came off the coat.", tip: "The letter ґ (hard g) distinguishes Ukrainian from Russian.", highlights: ["Ґ"] },
      { phrase: "Моє ім'я — Тарас.", translation: "My name is Taras.", tip: "Ukrainian uses the apostrophe inside words (ім'я), which Russian writes differently.", highlights: ["'", "є"] },
      { phrase: "Київ — це красиве місто.", translation: "Kyiv is a beautiful city.", tip: "The spelling 'Київ' (not 'Киев') and ї are Ukrainian.", highlights: ["ї", "і", "і"] },
      { phrase: "Добрий день, друже!", translation: "Good day, friend!", tip: "'Добрий' (not 'добрый') and vocative 'друже' mark Ukrainian.", highlights: ["Добрий", "друже"] },
      { phrase: "Ми живемо в Україні.", translation: "We live in Ukraine.", tip: "'Україні' with ї and і, and 'живемо' plural, are Ukrainian.", highlights: ["Україні", "ї", "і"] },
    ],
  },
  {
    lang: "Bulgarian",
    aliases: ["Български"],
    tag: "bg",
    variants: [
      { phrase: "Не разбирам какво казваш.", translation: "I don't understand what you're saying.", tip: "Cyrillic, but Bulgarian lacks Russian's ы, э, ё.", highlights: ["Не"] },
      { phrase: "България е много красива.", translation: "Bulgaria is very beautiful.", tip: "The letter 'ъ' is used as a mid-word vowel (schwa) — a Bulgarian giveaway.", highlights: ["ъ"] },
      { phrase: "Момчето чете книгата.", translation: "The boy is reading the book.", tip: "Definite article is a suffix: -то, -та, -ът (момче → момчето).", highlights: ["то", "та"] },
      { phrase: "Искам да ям нещо.", translation: "I want to eat something.", tip: "Bulgarian uses 'да + verb' instead of an infinitive.", highlights: ["да", "щ"] },
      { phrase: "Утре ще ходя на пазар.", translation: "Tomorrow I will go to the market.", tip: "Future tense uses 'ще' + verb — unique among Slavic languages.", highlights: ["ще"] },
      { phrase: "Благодаря ти за помощта.", translation: "Thank you for the help.", tip: "'Благодаря' for thanks and -та suffix for 'the help' are Bulgarian.", highlights: ["та"] },
      { phrase: "Жената работи в градината.", translation: "The woman works in the garden.", tip: "Definite suffix -та on feminine nouns: жена → жената.", highlights: ["та", "та"] },
      { phrase: "Слънцето грее ярко днес.", translation: "The sun is shining brightly today.", tip: "'Слънце' with 'ъ' as a real vowel and -то article is unmistakably Bulgarian.", highlights: ["ъ", "то"] },
    ],
  },
  {
    lang: "Serbian",
    aliases: ["Српски", "Srpski"],
    tag: "sr",
    variants: [
      { phrase: "Не разумем шта говориш.", translation: "I don't understand what you're saying.", tip: "Cyrillic Serbian uses letters like љ and њ that don't exist in Russian.", highlights: ["ш"] },
      { phrase: "Људи иду у биоскоп.", translation: "People are going to the cinema.", tip: "The letter 'љ' (capitalised Љ) is a Serbian Cyrillic letter (soft l).", highlights: ["Љ"] },
      { phrase: "Њена кућа је на брду.", translation: "Her house is on the hill.", tip: "'њ' (soft n) is a Serbian-exclusive Cyrillic letter.", highlights: ["Њ", "ћ"] },
      { phrase: "Ђак иде у школу.", translation: "The pupil is going to school.", tip: "The letter 'ђ' (soft d/j) is Serbian Cyrillic.", highlights: ["Ђ"] },
      { phrase: "Не razumem šta govoriš.", translation: "I don't understand what you're saying.", tip: "Serbian is fully bi-scriptal — same sentence in Latin uses š, č, ć, đ, ž.", highlights: ["š", "š"] },
      { phrase: "Đak ide u školu.", translation: "The pupil is going to school.", tip: "In Latin Serbian, 'đ' (crossed d) matches Cyrillic 'ђ'.", highlights: ["Đ", "š"] },
      { phrase: "Moja kuća je velika.", translation: "My house is big.", tip: "'kuća' (with ć) and 'šta' vs 'što' lean Serbian over Croatian.", highlights: ["ć"] },
      { phrase: "Где је твоја сестра?", translation: "Where is your sister?", tip: "Serbian says 'где' (not Russian 'где' — but 'је' for 'is' instead of 'есть').", highlights: ["је"] },
    ],
  },
  {
    lang: "Croatian",
    aliases: ["Hrvatski"],
    tag: "hr",
    variants: [
      { phrase: "Ne razumijem što govoriš.", translation: "I don't understand what you're saying.", tip: "Croatian uses 'što' (Serbian 'шта/šta'), and the ije reflex in 'razumijem'.", highlights: ["što", "ije"] },
      { phrase: "Čaša je na stolu.", translation: "The glass is on the table.", tip: "Latin with č (not Cyrillic) — Croatian never uses Cyrillic officially.", highlights: ["Č"] },
      { phrase: "Ćevapi su jako ukusni.", translation: "Ćevapi are very tasty.", tip: "The soft ć (distinct from č) is Croatian/Serbian/Bosnian.", highlights: ["Ć"] },
      { phrase: "Đurđica cvjeta u svibnju.", translation: "Lily of the valley blooms in May.", tip: "The letter 'đ' (crossed d) and month name 'svibanj' are Croatian.", highlights: ["Đ", "đ"] },
      { phrase: "Škola je zatvorena danas.", translation: "The school is closed today.", tip: "Š, č and Latin script together indicate Croatian (or Bosnian).", highlights: ["Š"] },
      { phrase: "Lijepo vrijeme za šetnju.", translation: "Nice weather for a walk.", tip: "The 'ije' diphthong (ijekavian) is Croatian — Serbian often uses 'e'.", highlights: ["ije", "ije"] },
      { phrase: "Žao mi je, ne znam.", translation: "I'm sorry, I don't know.", tip: "'Žao mi je' is a Croatian idiom; ž is a Slavic Latin letter.", highlights: ["Ž"] },
      { phrase: "Djevojka čita knjigu.", translation: "The girl is reading a book.", tip: "Croatian keeps 'dj/đ' and palatalized 'nj'/'lj' clusters.", highlights: ["Dj", "č", "nj"] },
    ],
  },
  {
    lang: "Slovenian",
    aliases: ["Slovenščina"],
    tag: "sl",
    variants: [
      { phrase: "Ne razumem, kaj praviš.", translation: "I don't understand what you're saying.", tip: "Slovenian uses 'kaj' (what) — not 'što' (Croatian) or 'шта' (Serbian).", highlights: ["kaj"] },
      { phrase: "Čaj je zelo vroč.", translation: "The tea is very hot.", tip: "Only č, š, ž as special letters — no ć, đ (that's Croatian/Serbian).", highlights: ["Č", "č"] },
      { phrase: "Šola je zaprta danes.", translation: "The school is closed today.", tip: "Slovenian has no ć or đ — that absence is itself a tell.", highlights: ["Š"] },
      { phrase: "Najlepša hvala za pomoč.", translation: "Thank you very much for your help.", tip: "'Hvala' (thanks) + Slovene superlative 'naj-' are typical.", highlights: ["Naj", "č"] },
      { phrase: "Midva greva v trgovino.", translation: "The two of us are going to the shop.", tip: "Slovenian retains the dual number — 'midva', 'greva' are two-person forms.", highlights: ["Midva", "va"] },
      { phrase: "Ljubljana je lepo mesto.", translation: "Ljubljana is a beautiful city.", tip: "'Ljubljana' itself + 'lj' cluster is a Slovenian spelling hint.", highlights: ["lj", "lj"] },
      { phrase: "Žal mi je, ne vem.", translation: "I'm sorry, I don't know.", tip: "'Žal mi je' and 'ne vem' are classic Slovene idioms.", highlights: ["Ž"] },
      { phrase: "Slovenščina je zanimiv jezik.", translation: "Slovenian is an interesting language.", tip: "The '-ščina' ending of language names and 'č' are Slovene.", highlights: ["ščina", "č"] },
    ],
  },
  {
    lang: "Albanian",
    aliases: ["Shqip"],
    tag: "sq",
    variants: [
      { phrase: "Nuk flas mirë shqip.", translation: "I don't speak Albanian well.", tip: "'Nuk' is the Albanian word for 'not'.", highlights: ["Nuk"] },
      { phrase: "Përshëndetje, si jeni sot?", translation: "Hello, how are you today?", tip: "The schwa ë appears in almost every Albanian sentence.", highlights: ["ë", "ë"] },
      { phrase: "Djali i vogël po lexon.", translation: "The little boy is reading.", tip: "Albanian 'dj' at word-start is not a digraph — unlike English it stays as d+j.", highlights: ["Dj"] },
      { phrase: "Një libër i ri në tavolinë.", translation: "A new book on the table.", tip: "'ë' ending is how the indefinite/definite split shows — a very Albanian feature.", highlights: ["ë", "ë"] },
      { phrase: "Xhami është pranë shtëpisë.", translation: "The mosque is near the house.", tip: "The digraph 'xh' (like English 'j') is Albanian.", highlights: ["Xh"] },
      { phrase: "Gjuha shqipe është e vjetër.", translation: "The Albanian language is old.", tip: "The 'gj' digraph (soft dy) is an Albanian letter combo.", highlights: ["Gj", "ë"] },
      { phrase: "Nxënësi shkon në shkollë.", translation: "The pupil goes to school.", tip: "The digraph 'nx' (like 'dz') is an Albanian-only cluster.", highlights: ["Nx", "ë"] },
      { phrase: "Rruga është shumë e gjatë.", translation: "The road is very long.", tip: "Double 'rr' (distinct sound from single r) is Albanian.", highlights: ["Rr", "ë", "ë"] },
    ],
  },
  {
    lang: "Lithuanian",
    aliases: ["Lietuvių"],
    tag: "lt",
    variants: [
      { phrase: "Nemoku gerai kalbėti lietuviškai.", translation: "I don't speak Lithuanian well.", tip: "The dot-above 'ė' is a Lithuanian letter.", highlights: ["ė"] },
      { phrase: "Mano draugas kalba lietuviškai.", translation: "My friend speaks Lithuanian.", tip: "Endings -as/-is/-us on masculine nouns are archaic-looking Lithuanian.", highlights: ["as"] },
      { phrase: "Ąžuolas auga sode.", translation: "The oak tree grows in the garden.", tip: "Ogonek vowels ą, ę, į, ų + háček ž mark Lithuanian.", highlights: ["Ą", "ž"] },
      { phrase: "Aš esu iš Vilniaus.", translation: "I am from Vilnius.", tip: "'Aš' for 'I' and '-us' genitive ending mark Lithuanian.", highlights: ["Aš", "us"] },
      { phrase: "Čia yra graži gėlė.", translation: "Here is a beautiful flower.", tip: "Háček č, š, ž in Latin script + ė is a Lithuanian profile.", highlights: ["Č", "ž", "ė", "ė"] },
      { phrase: "Mes einame į parduotuvę.", translation: "We are going to the shop.", tip: "Accusative case ending -ę (ogonek) stacks onto feminine nouns.", highlights: ["į", "ę"] },
      { phrase: "Šviesus rytas išaušta.", translation: "A bright morning is dawning.", tip: "'š' together with -us/-a endings and ogonek letters are Lithuanian.", highlights: ["Š", "us", "š"] },
      { phrase: "Tėvas ir sūnus važiuoja kartu.", translation: "Father and son are driving together.", tip: "Macron-like ū (with long mark) plus -as endings are Lithuanian.", highlights: ["ė", "ū"] },
    ],
  },
  {
    lang: "Latvian",
    aliases: ["Latviešu"],
    tag: "lv",
    variants: [
      { phrase: "Es nerunāju latviski labi.", translation: "I don't speak Latvian well.", tip: "Macron ā, ē, ī, ū mark long vowels in Latvian (not Lithuanian).", highlights: ["ā"] },
      { phrase: "Māja ir liela un skaista.", translation: "The house is big and beautiful.", tip: "Macrons over vowels (ā, ī) are a Latvian hallmark.", highlights: ["ā"] },
      { phrase: "Ģimene ēd vakariņas.", translation: "The family is eating dinner.", tip: "Comma-below letters ģ, ķ, ļ, ņ (palatals) are Latvian.", highlights: ["Ģ", "ē", "ņ"] },
      { phrase: "Šodien ir skaista diena.", translation: "Today is a beautiful day.", tip: "Háček Š plus the -s masculine endings are a Latvian profile.", highlights: ["Š"] },
      { phrase: "Rīga ir Latvijas galvaspilsēta.", translation: "Riga is the capital of Latvia.", tip: "Long ī in 'Rīga' plus -as genitive are Latvian.", highlights: ["ī", "ē"] },
      { phrase: "Meitene lasa grāmatu.", translation: "The girl is reading a book.", tip: "-ene feminine suffix and ā macron are Latvian.", highlights: ["ā"] },
      { phrase: "Čiekurs nokrita no egles.", translation: "The pine cone fell from the fir tree.", tip: "'Č' at the start plus -s masculine endings are Latvian.", highlights: ["Č", "s"] },
      { phrase: "Paldies par jūsu palīdzību.", translation: "Thank you for your help.", tip: "'Paldies' (thanks) with 'ū' and 'ī' macrons is Latvian.", highlights: ["ū", "ī"] },
    ],
  },
  {
    lang: "Estonian",
    aliases: ["Eesti"],
    tag: "et",
    variants: [
      { phrase: "Mu õde õpib eesti keelt.", translation: "My sister is learning Estonian.", tip: "The back-vowel 'õ' is Estonian (Portuguese uses it too, but the rest of the text won't look Portuguese).", highlights: ["õ", "õ", "ee"] },
      { phrase: "Raamatukogu on uus ja suur.", translation: "The library is new and big.", tip: "Lots of double vowels (aa, uu) — Estonian is Finno-Ugric like Finnish.", highlights: ["aa", "uu", "uu"] },
      { phrase: "Tüdruk sööb õuna.", translation: "The girl is eating an apple.", tip: "The combination õ + ü + ö in a sentence is an Estonian fingerprint.", highlights: ["ü", "öö", "õ"] },
      { phrase: "Tallinn on ilus linn.", translation: "Tallinn is a beautiful city.", tip: "Doubled consonants (nn, ll) to mark long sounds are Estonian.", highlights: ["nn", "nn"] },
      { phrase: "Mul on üks väike koer.", translation: "I have one small dog.", tip: "'Mul on' (I have) uses the adessive case — typical Estonian grammar.", highlights: ["Mul on", "ü"] },
      { phrase: "Täna on väga soe ilm.", translation: "Today is very warm weather.", tip: "Ä + ä in function words like 'täna' and 'väga' lean Estonian (not Finnish).", highlights: ["ä", "ä"] },
      { phrase: "Õpetaja räägib klassis.", translation: "The teacher is speaking in class.", tip: "Word-initial 'Õ' and present -b endings are Estonian.", highlights: ["Õ", "ää"] },
      { phrase: "Soome ja Eesti on naabrid.", translation: "Finland and Estonia are neighbours.", tip: "'Soome' for Finland and double-o 'oo' with 'e'-endings are Estonian.", highlights: ["oo", "Eesti"] },
    ],
  },
  {
    lang: "Catalan",
    aliases: ["Català"],
    tag: "ca",
    variants: [
      { phrase: "No parlo gaire bé el català.", translation: "I don't speak Catalan very well.", tip: "'Gaire' (much/very in negatives) is a Catalan marker.", highlights: ["gaire"] },
      { phrase: "Una paraula amb l·l al mig.", translation: "A word with l·l in the middle.", tip: "The 'l·l' (geminate l with middle dot) is unique to Catalan.", highlights: ["l·l"] },
      { phrase: "La plaça és molt gran.", translation: "The square is very big.", tip: "The cedilla ç is used before a/o/u, like French.", highlights: ["ç"] },
      { phrase: "Què fas ara mateix?", translation: "What are you doing right now?", tip: "The grave è (an open-e vowel) is Catalan — Spanish doesn't use it.", highlights: ["è"] },
      { phrase: "Açò és molt important.", translation: "This is very important.", tip: "'Açò' (this) + ç show the Catalan profile.", highlights: ["ç"] },
      { phrase: "El cafè és fred.", translation: "The coffee is cold.", tip: "Grave accent on final è is a Catalan/Italian spelling.", highlights: ["è"] },
      { phrase: "Bon dia, com estàs?", translation: "Good morning, how are you?", tip: "'Bon dia' and grave 'à' in 'estàs' mark Catalan.", highlights: ["à"] },
      { phrase: "M'agrada molt la música.", translation: "I really like the music.", tip: "Apostrophe contractions like m', l', n' are Catalan staples.", highlights: ["M'", "ú"] },
    ],
  },
  {
    lang: "Galician",
    aliases: ["Galego"],
    tag: "gl",
    variants: [
      { phrase: "Non falo moi ben galego.", translation: "I don't speak Galician well.", tip: "'Non' for 'no' (Spanish 'no', Portuguese 'não') is the Galician sign.", highlights: ["Non"] },
      { phrase: "A Xunta reúnese mañá.", translation: "The Xunta meets tomorrow.", tip: "'X' for the 'sh' sound (as in 'Xunta', 'xeito') is Galician.", highlights: ["X"] },
      { phrase: "O neno come unha mazá.", translation: "The boy is eating an apple.", tip: "Unhedged article 'unha' and 'o/a' without 'l' — Galician vs Portuguese 'uma'.", highlights: ["unha", "á"] },
      { phrase: "A información é importante.", translation: "Information is important.", tip: "Like Portuguese '-ção', Galician uses '-ción' (like Spanish).", highlights: ["ción"] },
      { phrase: "Onde está a miña casa?", translation: "Where is my house?", tip: "'miña' (my, fem.) with ñ + tilde í on 'á' are Galician.", highlights: ["ñ", "á"] },
      { phrase: "Estou moi canso hoxe.", translation: "I am very tired today.", tip: "'hoxe' (today) with x for sh — classic Galician.", highlights: ["x", "n"] },
      { phrase: "A chuvia cae na rúa.", translation: "The rain is falling on the street.", tip: "'chuvia' (rain) + 'rúa' with acute ú are Galician.", highlights: ["ú"] },
      { phrase: "Grazas pola túa axuda.", translation: "Thanks for your help.", tip: "'Grazas' (not Spanish 'gracias', not Portuguese 'obrigado') is Galician.", highlights: ["Grazas", "ú", "x"] },
    ],
  },
  {
    lang: "Basque",
    aliases: ["Euskara"],
    tag: "eu",
    variants: [
      { phrase: "Ez dakit euskaraz ondo hitz egiten.", translation: "I don't know how to speak Basque well.", tip: "'Ez' is the Basque negator; 'euskaraz' itself is a dead giveaway.", highlights: ["Ez", "euskaraz"] },
      { phrase: "Kaixo, zer moduz zaude?", translation: "Hello, how are you?", tip: "'Kaixo' (hello) is famously Basque; z + k pepper the language.", highlights: ["Kaixo", "z"] },
      { phrase: "Txakurra parkera doa.", translation: "The dog is going to the park.", tip: "The digraph 'tx' (like English 'ch') is Basque.", highlights: ["Tx"] },
      { phrase: "Eskerrik asko zure laguntzagatik.", translation: "Thank you very much for your help.", tip: "'Eskerrik asko' (thanks a lot) + -tz cluster are Basque.", highlights: ["Eskerrik asko", "tz"] },
      { phrase: "Etxea mendian dago.", translation: "The house is on the mountain.", tip: "'Etxea' (the house) with 'tx' shows the Basque article -a suffix.", highlights: ["Etx", "a"] },
      { phrase: "Gizonak euskara ikasten du.", translation: "The man is learning Basque.", tip: "Ergative suffix -ak (here on 'gizonak') marks the subject of a transitive verb.", highlights: ["ak"] },
      { phrase: "Bilbon bizi naiz.", translation: "I live in Bilbao.", tip: "'Bilbon' (inessive) + 'naiz' (am) are Basque verb/case patterns.", highlights: ["Bilbon", "naiz"] },
      { phrase: "Zazpi behi zelaian daude.", translation: "Seven cows are in the field.", tip: "'Zazpi' (seven) and -an locative on 'zelaia' are Basque staples.", highlights: ["Zazpi", "an"] },
    ],
  },
  {
    lang: "Welsh",
    aliases: ["Cymraeg"],
    tag: "cy",
    variants: [
      { phrase: "Dwi ddim yn siarad Cymraeg yn dda.", translation: "I don't speak Welsh well.", tip: "The 'dd' digraph (voiced 'th') is a Welsh letter combo.", highlights: ["dd", "dd"] },
      { phrase: "Mae'r llyfr ar y bwrdd.", translation: "The book is on the table.", tip: "The 'll' digraph (voiceless lateral fricative) is famously Welsh.", highlights: ["ll"] },
      { phrase: "Rydw i'n hoffi cwrw cryf.", translation: "I like strong beer.", tip: "'w' acts as a vowel (as in 'cwrw' = beer) — very Welsh.", highlights: ["w", "w", "w"] },
      { phrase: "Mae Cymru yn wlad hardd.", translation: "Wales is a beautiful country.", tip: "'y' as a vowel (as in 'Cymru') is another Welsh tell.", highlights: ["y", "y"] },
      { phrase: "Pnawn da, sut wyt ti?", translation: "Good afternoon, how are you?", tip: "Consonant clusters like 'pn-' at word start plus 'wy' diphthong mark Welsh.", highlights: ["Pn", "wy"] },
      { phrase: "Rhedodd y plentyn drwy'r ardd.", translation: "The child ran through the garden.", tip: "The digraph 'rh' (voiceless trilled r) is Welsh-exclusive.", highlights: ["Rh", "dd"] },
      { phrase: "Ffenestr y tŷ yw'r drws.", translation: "The window of the house is the door.", tip: "The circumflex 'tô bach' on ŷ and the 'Ff' digraph mark Welsh.", highlights: ["Ff", "ŷ"] },
      { phrase: "Dw i'n caru Cymru am byth.", translation: "I love Wales forever.", tip: "Mutations (c→g, p→b) and 'dw i' / 'byth' are Welsh staples.", highlights: ["Cymru", "yth"] },
    ],
  },
  {
    lang: "Irish",
    aliases: ["Gaeilge", "Irish Gaelic"],
    tag: "ga",
    variants: [
      { phrase: "Níl Gaeilge mhaith agam.", translation: "I don't have good Irish.", tip: "Acute 'síneadh fada' on vowels (á é í ó ú) marks length in Irish.", highlights: ["í"] },
      { phrase: "Tá an lá go hálainn.", translation: "The day is beautiful.", tip: "'Tá' (is) + 'go h-' are Irish syntactic tells.", highlights: ["á", "á"] },
      { phrase: "Bhí mé ag siúl ar an trá.", translation: "I was walking on the beach.", tip: "The lenited cluster 'bh' (pronounced v or w) is an Irish consonant mutation.", highlights: ["Bh", "ú", "á"] },
      { phrase: "Chuir sí ceist ar a mháthair.", translation: "She asked her mother a question.", tip: "Lenition to 'ch' and 'mh' is a Celtic Irish fingerprint.", highlights: ["Ch", "mh"] },
      { phrase: "Dhún an doras go tapa.", translation: "The door closed quickly.", tip: "Lenition 'dh' (silent or like 'gh') is a classic Irish mutation.", highlights: ["Dh"] },
      { phrase: "Tá mo sheanathair ag teacht.", translation: "My grandfather is coming.", tip: "Lenition 'sh' (= h) softens words after possessives.", highlights: ["sh"] },
      { phrase: "Is maith liom caife láidir.", translation: "I like strong coffee.", tip: "'Is maith liom' (I like) is a defining Irish idiom.", highlights: ["Is maith liom", "á"] },
      { phrase: "Beidh an aimsir go breá amárach.", translation: "The weather will be fine tomorrow.", tip: "'amárach' (tomorrow) + broad/slender vowels (a-i-a) are Irish spelling rules.", highlights: ["á", "á"] },
    ],
  },
  {
    lang: "Scottish Gaelic",
    aliases: ["Gàidhlig", "Scots Gaelic"],
    tag: "gd",
    variants: [
      { phrase: "Chan eil Gàidhlig mhath agam.", translation: "I don't have good Gaelic.", tip: "Scottish Gaelic uses GRAVE accents (à è ì ò ù), not acute like Irish.", highlights: ["à"] },
      { phrase: "Tha an latha brèagha an-diugh.", translation: "The day is beautiful today.", tip: "'Tha' + grave 'è' distinguish Scottish from Irish.", highlights: ["è"] },
      { phrase: "Bha mi ann am Glaschu an-dè.", translation: "I was in Glasgow yesterday.", tip: "The word 'Glaschu' + 'an-dè' are Scottish Gaelic spellings.", highlights: ["è"] },
      { phrase: "Chan eil fhios agam.", translation: "I don't know.", tip: "'Chan eil' is the negative of 'is/are' — a Scottish Gaelic signature.", highlights: ["Chan eil"] },
      { phrase: "Tha mi duilich, tha mi sgìth.", translation: "I'm sorry, I'm tired.", tip: "Grave ì + broad/slender spelling rules mark Scottish Gaelic.", highlights: ["ì"] },
      { phrase: "'S e latha math a th' ann.", translation: "It's a good day.", tip: "The copula ''s e' (it is) + apostrophes are Scottish Gaelic staples.", highlights: ["'S e", "th'"] },
      { phrase: "Bidh mi a' tilleadh a-màireach.", translation: "I'll be returning tomorrow.", tip: "Progressive 'a' + verbal noun' construction is classic Scottish Gaelic.", highlights: ["a'", "à"] },
      { phrase: "Tha a' ghrian a' deàlradh gu h-àrd.", translation: "The sun is shining high.", tip: "Multiple grave accents + lenition 'ghr-' mark Scottish Gaelic.", highlights: ["à", "à"] },
    ],
  },
  {
    lang: "Latin",
    aliases: ["Lingua Latina"],
    tag: "la",
    variants: [
      { phrase: "Latine non bene loquor.", translation: "I don't speak Latin well.", tip: "No diacritics at all, and verb at the end — classic Latin.", highlights: ["loquor"] },
      { phrase: "Veni, vidi, vici.", translation: "I came, I saw, I conquered.", tip: "Perfect tense endings in -i form the iconic Caesar quote.", highlights: ["vici"] },
      { phrase: "Puer puellam amat.", translation: "The boy loves the girl.", tip: "Case endings do the work of word order: puer (nom.) → puellam (acc.).", highlights: ["am", "at"] },
      { phrase: "Senatus populusque Romanus.", translation: "The Senate and People of Rome.", tip: "The enclitic '-que' (= 'and') attaches to the end of the second word.", highlights: ["que"] },
      { phrase: "Nomen mihi est Marcus.", translation: "My name is Marcus.", tip: "'Nomen' (name) + dative 'mihi' + 'est' (is) is the Latin idiom.", highlights: ["est"] },
      { phrase: "Omnia vincit amor.", translation: "Love conquers all.", tip: "'Omnia' (all things, neuter plural) shows Latin neuter -a plurals.", highlights: ["Omnia"] },
      { phrase: "Libri magistri sunt in mensa.", translation: "The teacher's books are on the table.", tip: "Genitive '-i' (magistri = of the teacher) does the work of 'of'.", highlights: ["i", "i"] },
      { phrase: "Ad astra per aspera.", translation: "To the stars through difficulties.", tip: "Prepositions (ad, per) + noun endings a/ae/is/um distinguish Latin.", highlights: ["Ad", "per"] },
    ],
  },
  {
    lang: "Esperanto",
    aliases: [],
    tag: "eo",
    variants: [
      { phrase: "Mi ne parolas Esperanton tre bone.", translation: "I don't speak Esperanto very well.", tip: "Accusative -n suffix on 'Esperanton' marks a direct object — Esperanto's trademark.", highlights: ["n"] },
      { phrase: "La suno brilas hodiaŭ.", translation: "The sun is shining today.", tip: "The breve 'ŭ' (u with breve) appears only in Esperanto.", highlights: ["ŭ"] },
      { phrase: "Ĉu vi parolas Esperanton?", translation: "Do you speak Esperanto?", tip: "Questions start with 'Ĉu'; circumflex Ĉ is Esperanto.", highlights: ["Ĉ"] },
      { phrase: "La ĝardeno estas bela.", translation: "The garden is beautiful.", tip: "The letter ĝ (with circumflex) is Esperanto's /dʒ/ sound.", highlights: ["ĝ"] },
      { phrase: "Ĥoroj kantas en ĥoruso.", translation: "Choirs sing in chorus.", tip: "ĥ (with circumflex, like 'kh') is a rarely used Esperanto letter.", highlights: ["Ĥ", "ĥ"] },
      { phrase: "La birdoj flugas al la ĉielo.", translation: "The birds fly to the sky.", tip: "All nouns end in -o, all plurals in -oj.", highlights: ["oj", "o", "ĉ"] },
      { phrase: "Ŝi ŝatas la belan floron.", translation: "She likes the beautiful flower.", tip: "ŝ (circumflex s) is the /ʃ/ sound — an Esperanto letter.", highlights: ["Ŝ", "ŝ", "n"] },
      { phrase: "La libroj estas sur la tablo.", translation: "The books are on the table.", tip: "Every noun -o, adj -a, verb -as — the regular Esperanto toolkit.", highlights: ["oj", "as", "o"] },
    ],
  },
  {
    lang: "Afrikaans",
    aliases: [],
    tag: "af",
    variants: [
      { phrase: "Ek praat nie baie goed Afrikaans nie.", translation: "I don't speak Afrikaans very well.", tip: "Double-negative 'nie … nie' wrapping the verb is Afrikaans's signature.", highlights: ["nie", "nie"] },
      { phrase: "Ek is baie bly om jou te sien.", translation: "I am very glad to see you.", tip: "'Ek' for 'I' (shorter than Dutch 'ik') and 'baie' (very) mark Afrikaans.", highlights: ["Ek", "baie"] },
      { phrase: "Ons gaan saam na die strand.", translation: "We're going together to the beach.", tip: "'Saam' and 'die' (for 'the') are typical Afrikaans.", highlights: ["saam", "die"] },
      { phrase: "Die kat is op die dak.", translation: "The cat is on the roof.", tip: "Every 'the' is 'die' — invariant across genders, a Simplified-Dutch trait.", highlights: ["Die", "die"] },
      { phrase: "Ek het my sleutels verloor.", translation: "I have lost my keys.", tip: "Perfect tense with 'het + past participle' (no inflection) is Afrikaans simple.", highlights: ["het", "ver"] },
      { phrase: "Hy is jammer, hy kan nie kom nie.", translation: "He is sorry, he can't come.", tip: "'Jammer' (sorry) and the classic double-nie pattern are Afrikaans.", highlights: ["jammer", "nie", "nie"] },
      { phrase: "Môre gaan ons piekniek hou.", translation: "Tomorrow we're having a picnic.", tip: "The circumflex kappie on 'Môre' (= tomorrow) is Afrikaans.", highlights: ["ô"] },
      { phrase: "Die meisie lees 'n boek.", translation: "The girl is reading a book.", tip: "The indefinite article 'n (always contracted) is distinctly Afrikaans.", highlights: ["'n"] },
    ],
  },
  {
    lang: "Swahili",
    aliases: ["Kiswahili"],
    tag: "sw",
    variants: [
      { phrase: "Sisemi Kiswahili vizuri sana.", translation: "I don't speak Swahili very well.", tip: "The 'Ki-' prefix on language names (Kiswahili, Kiingereza) is Swahili.", highlights: ["Ki"] },
      { phrase: "Mtoto anasoma kitabu.", translation: "The child is reading a book.", tip: "Noun-class prefixes: m- (person), ki- (thing), mw- (human) — very Bantu.", highlights: ["M", "ki"] },
      { phrase: "Watoto wanacheza uwanjani.", translation: "The children are playing in the yard.", tip: "Plural 'Wa-' prefix + agreement 'wa-' on the verb are Bantu.", highlights: ["Wa", "wa"] },
      { phrase: "Ninakupenda sana.", translation: "I love you very much.", tip: "Verb is built of prefixes: Ni- (I) + na- (present) + ku- (you) + stem.", highlights: ["Ni", "na", "ku"] },
      { phrase: "Nataka kula chakula.", translation: "I want to eat food.", tip: "'Ch-' class (chakula = food) and 'Ku-' infinitive prefix are Swahili.", highlights: ["ku", "ch"] },
      { phrase: "Jambo, habari gani?", translation: "Hello, what's the news?", tip: "'Jambo' is a classic Swahili greeting.", highlights: ["Jambo", "habari"] },
      { phrase: "Asante sana kwa msaada.", translation: "Thanks a lot for the help.", tip: "'Asante' for thanks and 'kwa' for 'with/for' are Swahili staples.", highlights: ["Asante", "kwa"] },
      { phrase: "Nyumba yangu ni nzuri.", translation: "My house is nice.", tip: "Class-9 'N-' nouns (nyumba = house) and the 'nz' cluster mark Swahili.", highlights: ["Ny", "nz"] },
    ],
  },
  {
    lang: "Indonesian",
    aliases: ["Bahasa Indonesia", "Malay", "Bahasa Melayu"],
    tag: "id",
    variants: [
      { phrase: "Saya tidak bisa berbahasa Indonesia dengan baik.", translation: "I can't speak Indonesian well.", tip: "Latin alphabet, no diacritics or tones, and prefixes like 'ber-' mark Indonesian.", highlights: ["ber"] },
      { phrase: "Anak-anak bermain di taman.", translation: "The children play in the park.", tip: "Reduplication 'Anak-anak' (children) is a characteristic plural marker.", highlights: ["Anak-anak"] },
      { phrase: "Saya mencintai buku itu.", translation: "I love that book.", tip: "The 'men-' active-verb prefix (with mutation) is Indonesian.", highlights: ["men"] },
      { phrase: "Dia terjatuh di jalan.", translation: "He fell on the road.", tip: "The 'ter-' prefix (accidental/passive) is an Indonesian marker.", highlights: ["ter"] },
      { phrase: "Tolong kirimkan surat ini.", translation: "Please send this letter.", tip: "Suffixes '-kan' (benefactive) and '-i' (locative) on verbs mark Indonesian.", highlights: ["kan", "ini"] },
      { phrase: "Selamat pagi, apa kabar?", translation: "Good morning, how are you?", tip: "'Selamat' greetings and 'apa kabar' are Indonesian/Malay staples.", highlights: ["Selamat", "apa kabar"] },
      { phrase: "Rumah saya besar dan indah.", translation: "My house is big and beautiful.", tip: "Possessive follows the noun ('rumah saya' = my house), with no inflection.", highlights: ["saya"] },
      { phrase: "Orang-orang itu sangat ramah.", translation: "Those people are very friendly.", tip: "Reduplication 'Orang-orang' (people) + 'itu' (that) are Indonesian signatures.", highlights: ["Orang-orang", "itu"] },
    ],
  },
  {
    lang: "Tagalog",
    aliases: ["Filipino"],
    tag: "tl",
    variants: [
      { phrase: "Hindi ako magaling magsalita ng Tagalog.", translation: "I'm not good at speaking Tagalog.", tip: "'Hindi' (= not) and 'ng' (genitive marker, pronounced 'nang') are Tagalog giveaways.", highlights: ["Hindi", "ng"] },
      { phrase: "Mahal kita nang sobra.", translation: "I love you so much.", tip: "'Mahal kita' is a Tagalog idiom; 'nang' is the adverbial linker.", highlights: ["Mahal kita", "nang"] },
      { phrase: "Kumain ka na ba?", translation: "Have you eaten?", tip: "Question particle 'ba' + aspect infix 'um' (kumain < kain) are Tagalog.", highlights: ["um", "ba"] },
      { phrase: "Magandang umaga sa inyong lahat.", translation: "Good morning to you all.", tip: "Mag- prefix + -ng linker ('Magandang') are Tagalog syntax.", highlights: ["Mag", "ng"] },
      { phrase: "Ang mga bata ay naglalaro sa labas.", translation: "The children are playing outside.", tip: "Ang + mga = the (plural) — a Tagalog hallmark.", highlights: ["Ang", "mga"] },
      { phrase: "Pupunta ako sa Maynila bukas.", translation: "I will go to Manila tomorrow.", tip: "Reduplication 'pu-punta' marks future tense.", highlights: ["Pu", "pu"] },
      { phrase: "Salamat po sa inyong tulong.", translation: "Thank you for your help.", tip: "'Salamat' (thanks) + politeness particle 'po' are Tagalog staples.", highlights: ["Salamat", "po", "ng"] },
      { phrase: "Kaibigan ko siya mula pa noon.", translation: "He/she has been my friend for a long time.", tip: "'Siya' (gender-neutral he/she) and 'mula pa noon' are Tagalog.", highlights: ["Kaibigan", "siya"] },
    ],
  },
  {
    lang: "Vietnamese",
    aliases: ["Tiếng Việt"],
    tag: "vi",
    variants: [
      { phrase: "Tôi không nói tiếng Việt giỏi.", translation: "I don't speak Vietnamese well.", tip: "Stacked tone marks (a single vowel with two diacritics) are uniquely Vietnamese.", highlights: ["ế", "ệ"] },
      { phrase: "Đây là nhà của tôi.", translation: "This is my house.", tip: "The barred 'đ' (separate letter from d) is Vietnamese.", highlights: ["Đ"] },
      { phrase: "Chào bạn, bạn khỏe không?", translation: "Hello, how are you?", tip: "All-monosyllabic words written with spaces between them — classic Vietnamese.", highlights: ["Chào", "khỏe"] },
      { phrase: "Tôi muốn uống cà phê.", translation: "I want to drink coffee.", tip: "'ơ' and 'ư' with horn diacritic, plus tone marks on top — Vietnamese.", highlights: ["ố", "ô"] },
      { phrase: "Bà tôi rất thương cháu.", translation: "My grandmother loves her grandchildren very much.", tip: "Stacked diacritics on vowels (à, ấ, ú) are Vietnamese.", highlights: ["à", "ấ", "ươ"] },
      { phrase: "Đi chợ mua rau nhé!", translation: "Let's go to the market to buy vegetables!", tip: "Final particle 'nhé' and tone marks on every syllable mark Vietnamese.", highlights: ["Đ", "ợ", "é"] },
      { phrase: "Tôi đang học tiếng Việt.", translation: "I'm learning Vietnamese.", tip: "Progressive aspect marker 'đang' + 'tiếng + language' pattern.", highlights: ["đang", "ế", "ệ"] },
      { phrase: "Sáng nay trời rất đẹp.", translation: "This morning the weather is really beautiful.", tip: "Tones stacked on top of vowels (á, ờ, ấ, ẹ) are Vietnamese signatures.", highlights: ["á", "ờ", "ấ", "ẹ"] },
    ],
  },
  {
    lang: "Korean",
    aliases: ["한국어", "Hangugeo"],
    tag: "ko",
    variants: [
      { phrase: "저는 한국어를 잘 못해요.", translation: "I don't speak Korean well.", tip: "Hangul syllable blocks arranged in squares, no Chinese characters — Korean.", highlights: ["한국어"] },
      { phrase: "안녕하세요, 만나서 반가워요.", translation: "Hello, nice to meet you.", tip: "'안녕하세요' is the canonical Korean greeting.", highlights: ["안녕하세요"] },
      { phrase: "밥 먹었어요?", translation: "Have you eaten?", tip: "Question ending '어요?' and polite past '-었-' are Korean.", highlights: ["어요"] },
      { phrase: "감사합니다 정말로.", translation: "Thank you very much.", tip: "'감사합니다' (formal thanks) and '-ㅂ니다' polite ending are Korean.", highlights: ["감사합니다"] },
      { phrase: "저는 서울에 살아요.", translation: "I live in Seoul.", tip: "Locative particle '-에' and polite '-아요' mark Korean.", highlights: ["에", "아요"] },
      { phrase: "오늘 날씨가 좋네요.", translation: "The weather is nice today.", tip: "Topic particle '이/가' and final '-네요' (mild exclamation) are Korean.", highlights: ["가", "네요"] },
      { phrase: "이것은 제 책입니다.", translation: "This is my book.", tip: "'입니다' (the copula, formal) and 은/는 topic markers are Korean.", highlights: ["입니다", "은"] },
      { phrase: "뭐 먹을래요?", translation: "What do you want to eat?", tip: "'뭐' (what) + '-ㄹ래요' (will/want to) are Korean conversational forms.", highlights: ["뭐", "래요"] },
    ],
  },
  {
    lang: "Japanese",
    aliases: ["日本語", "Nihongo"],
    tag: "ja",
    variants: [
      { phrase: "日本語があまり上手ではありません。", translation: "I'm not very good at Japanese.", tip: "Mixing kanji + hiragana in the same sentence = Japanese.", highlights: ["日本語"] },
      { phrase: "こんにちは、お元気ですか？", translation: "Hello, how are you?", tip: "Hiragana (curvy: こ, ん, は) mixed with kanji marks Japanese.", highlights: ["こんにちは", "お"] },
      { phrase: "コーヒーを一杯ください。", translation: "One cup of coffee, please.", tip: "Katakana (angular: コ, ー, ヒ) marks loanwords in Japanese.", highlights: ["コーヒー"] },
      { phrase: "私は学生です。", translation: "I am a student.", tip: "Final 'です' (polite copula) is a classic Japanese ending.", highlights: ["です"] },
      { phrase: "東京の桜はとても綺麗です。", translation: "The cherry blossoms in Tokyo are very beautiful.", tip: "Kanji + hiragana particles like 'の' and 'は' mark Japanese.", highlights: ["の", "は"] },
      { phrase: "すみません、駅はどこですか？", translation: "Excuse me, where is the station?", tip: "Question particle 'か？' and hiragana clouds mark Japanese.", highlights: ["か？", "どこ"] },
      { phrase: "ありがとうございます。", translation: "Thank you very much.", tip: "All-hiragana formal thanks + the long-vowel mark 'う' are Japanese.", highlights: ["ありがとう"] },
      { phrase: "毎日本を読みます。", translation: "I read a book every day.", tip: "Verb ending 'ます' + object particle 'を' are Japanese.", highlights: ["ます", "を"] },
    ],
  },
  {
    lang: "Chinese",
    aliases: ["Mandarin", "中文", "普通话", "Putonghua", "Simplified Chinese", "Traditional Chinese"],
    tag: "zh",
    variants: [
      { phrase: "我不太会说中文。", translation: "I can't speak Chinese very well.", tip: "Solid block of Hanzi with no hiragana/katakana = Chinese (not Japanese).", highlights: ["中文"] },
      { phrase: "你好，你叫什么名字？", translation: "Hello, what's your name?", tip: "'你好' (hello) and question word '什么' are Chinese staples.", highlights: ["你好", "什么"] },
      { phrase: "我是学生。", translation: "I am a student.", tip: "'是' acts as 'am/is/are' — the Chinese copula.", highlights: ["是"] },
      { phrase: "他正在吃饭。", translation: "He is eating (right now).", tip: "'正在 + verb' marks present progressive in Chinese.", highlights: ["正在"] },
      { phrase: "这本书很有意思。", translation: "This book is very interesting.", tip: "Measure word '本' (for books) between demonstrative and noun is Chinese.", highlights: ["本", "很"] },
      { phrase: "我已经吃过饭了。", translation: "I've already eaten.", tip: "Aspect particles '过' (experiential) and '了' (completion) mark Chinese.", highlights: ["过", "了"] },
      { phrase: "谢谢你的帮助。", translation: "Thank you for your help.", tip: "'谢谢' for thanks + possessive '的' are Chinese essentials.", highlights: ["谢谢", "的"] },
      { phrase: "明天我要去北京。", translation: "Tomorrow I'm going to Beijing.", tip: "'要 + verb' for future intention and '去' (go) are Chinese patterns.", highlights: ["要", "去"] },
    ],
  },
  {
    lang: "Thai",
    aliases: ["ภาษาไทย"],
    tag: "th",
    variants: [
      { phrase: "ฉันพูดภาษาไทยไม่เก่ง", translation: "I don't speak Thai well.", tip: "Thai script has tall loops and hooks; no spaces between words in a clause.", highlights: ["ภาษาไทย"] },
      { phrase: "สวัสดีครับ สบายดีไหม", translation: "Hello, how are you?", tip: "'สวัสดี' is the classic Thai greeting; no word-internal spaces.", highlights: ["สวัสดี"] },
      { phrase: "ผมรักคุณมาก", translation: "I love you very much.", tip: "Circle-headed characters with loops above/below the baseline are Thai.", highlights: ["ผม", "คุณ"] },
      { phrase: "ข้าวผัดอร่อยมาก", translation: "The fried rice is very tasty.", tip: "Tone marks stacked above letters (like '่') are Thai.", highlights: ["่", "้"] },
      { phrase: "โรงเรียนอยู่ใกล้บ้าน", translation: "The school is near the house.", tip: "Lead vowels (เ, แ, โ, ใ, ไ) appear BEFORE the consonant they sound after.", highlights: ["โ", "ใ"] },
      { phrase: "ขอบคุณมากครับ", translation: "Thank you very much.", tip: "'ขอบคุณ' for thanks + gender particle 'ครับ' are Thai.", highlights: ["ขอบคุณ", "ครับ"] },
      { phrase: "วันนี้อากาศดีมาก", translation: "Today the weather is very good.", tip: "Tall-stemmed consonants (ว, น) + 'มาก' (very) are Thai staples.", highlights: ["วันนี้", "มาก"] },
      { phrase: "ฉันอยากกินผลไม้", translation: "I want to eat fruit.", tip: "No spaces between words, and tone marks perch above consonants.", highlights: ["ฉัน", "ไม้"] },
    ],
  },
  {
    lang: "Khmer",
    aliases: ["Cambodian", "ភាសាខ្មែរ"],
    tag: "km",
    variants: [
      { phrase: "ខ្ញុំមិនចេះភាសាខ្មែរទេ។", translation: "I don't know Khmer.", tip: "Subscript consonants (little glyphs hanging below the baseline) are Khmer.", highlights: ["ខ្ញុំ", "ខ្មែរ"] },
      { phrase: "សួស្តី តើអ្នកសុខសប្បាយទេ?", translation: "Hello, are you well?", tip: "'សួស្តី' is the Khmer greeting; dense, curly letterforms mark Khmer.", highlights: ["សួស្តី"] },
      { phrase: "អរគុណច្រើន។", translation: "Thank you very much.", tip: "The Khmer sentence ends with '។' (khan) — a distinctive punctuation.", highlights: ["។"] },
      { phrase: "ផ្ទះរបស់ខ្ញុំនៅជិតសាលា។", translation: "My house is near the school.", tip: "Stacked subscript consonants (e.g. ្ទ, ្ញ) define the Khmer script.", highlights: ["្ទ", "្ញ"] },
      { phrase: "ខ្ញុំចង់ញ៉ាំបាយ។", translation: "I want to eat rice.", tip: "'ខ្ញុំ' (I) and subscripts hanging below letters are Khmer.", highlights: ["ខ្ញុំ", "ញ៉"] },
      { phrase: "ថ្ងៃនេះអាកាសធាតុល្អ។", translation: "Today the weather is good.", tip: "Vowel diacritics surround consonants on all sides — a Brahmic feature in Khmer.", highlights: ["្ង", "្អ"] },
      { phrase: "ខ្ញុំរៀនភាសាខ្មែរ។", translation: "I am learning Khmer.", tip: "The word 'ភាសា' (language) is followed by the language name.", highlights: ["ភាសា", "ខ្មែរ"] },
      { phrase: "សៀវភៅនេះគួរឲ្យចាប់អារម្មណ៍។", translation: "This book is interesting.", tip: "Long words with many subscripts + '។' terminator are Khmer.", highlights: ["្យ", "្ម"] },
    ],
  },
  {
    lang: "Arabic",
    aliases: ["العربية"],
    tag: "ar",
    variants: [
      { phrase: "أنا لا أتكلم العربية جيداً.", translation: "I don't speak Arabic well.", tip: "Right-to-left cursive Arabic script with connected letters — no p, v, or g.", highlights: ["العربية"] },
      { phrase: "السلام عليكم ورحمة الله.", translation: "Peace be upon you and God's mercy.", tip: "The definite article 'ال' (al-) attaches to nouns.", highlights: ["ال"] },
      { phrase: "كيف حالك اليوم؟", translation: "How are you today?", tip: "The Arabic question mark '؟' is a mirror of the Western one.", highlights: ["؟"] },
      { phrase: "هذا بيت جميل جداً.", translation: "This is a very beautiful house.", tip: "'هذا' (this, m.) + tanwin 'ً' (indefinite ending) are Arabic.", highlights: ["هذا", "ً"] },
      { phrase: "ذهبت إلى السوق أمس،", translation: "I went to the market yesterday,", tip: "The Arabic comma '،' slants opposite to the Western one.", highlights: ["،"] },
      { phrase: "شكراً جزيلاً على مساعدتك.", translation: "Thanks a lot for your help.", tip: "'شكراً' with tanwin '-an' ending is classical Arabic for 'thanks'.", highlights: ["شكراً"] },
      { phrase: "هي تعيش في مدينة كبيرة.", translation: "She lives in a big city.", tip: "'هي' (she) + ت- prefix on present-tense verbs mark Arabic grammar.", highlights: ["هي", "ت"] },
      { phrase: "المدرسة قريبة من البيت.", translation: "The school is near the house.", tip: "The ta marbuta 'ة' (feminine ending) appears twice here — Arabic signature.", highlights: ["ة", "ة"] },
    ],
  },
  {
    lang: "Persian",
    aliases: ["Farsi", "فارسی"],
    tag: "fa",
    variants: [
      { phrase: "پسر من پزشک است.", translation: "My son is a doctor.", tip: "The letter 'پ' (pe) is one of four Persian additions to the Arabic script.", highlights: ["پ", "پ"] },
      { phrase: "چای سرد است.", translation: "The tea is cold.", tip: "The letter 'چ' (che) is Persian/Urdu, not Arabic.", highlights: ["چ"] },
      { phrase: "ژاپن کشور بزرگی است.", translation: "Japan is a big country.", tip: "The letter 'ژ' (zhe) is exclusive to Persian-family scripts.", highlights: ["ژ"] },
      { phrase: "گل زیبایی در باغ است.", translation: "There is a beautiful flower in the garden.", tip: "The letter 'گ' (gaf) is Persian — Arabic has no 'g'.", highlights: ["گ"] },
      { phrase: "من به مدرسه می‌روم.", translation: "I go to school.", tip: "ZWNJ inside 'می‌روم' separates the prefix می- from the verb — Persian style.", highlights: ["می‌", "م"] },
      { phrase: "کتاب من روی میز است.", translation: "My book is on the table.", tip: "'است' (is) at sentence end and 'ی' (ye) with a hook are Persian.", highlights: ["است", "ی"] },
      { phrase: "خانه‌ی زیبا در تهران", translation: "A beautiful house in Tehran", tip: "The izafe (shown as ‌ی here) linking noun + adjective is a Persian grammar marker.", highlights: ["‌ی"] },
      { phrase: "سلام، حال شما چطور است؟", translation: "Hello, how are you?", tip: "'سلام' greeting + 'چطور' (how) and Persian-specific letters mark Farsi.", highlights: ["چ", "ط"] },
    ],
  },
  {
    lang: "Urdu",
    aliases: ["اردو"],
    tag: "ur",
    variants: [
      { phrase: "مجھے اردو اچھی طرح نہیں آتی۔", translation: "I don't know Urdu well.", tip: "Nastaliq (slanted, flowing script) + retroflex 'ٹ' mark Urdu.", highlights: ["اردو"] },
      { phrase: "آپ کیسے ہیں؟", translation: "How are you?", tip: "'آپ' (you, polite) + 'ہیں' (are) is an Urdu staple.", highlights: ["آپ", "ہیں"] },
      { phrase: "ٹماٹر لال ہے۔", translation: "The tomato is red.", tip: "Retroflex letters ٹ, ڈ, ڑ (with a small ط on top) are Urdu/Hindi sounds absent in Arabic.", highlights: ["ٹ"] },
      { phrase: "لڑکا سکول جاتا ہے۔", translation: "The boy goes to school.", tip: "The retroflex ڑ + '۔' (Urdu full stop) are distinctive.", highlights: ["ڑ", "۔"] },
      { phrase: "یہ کتاب میری ہے۔", translation: "This book is mine.", tip: "'یہ' (this) + 'ہے' (is) — Urdu uses Persian-Arabic script for Indo-Aryan grammar.", highlights: ["یہ", "ہے"] },
      { phrase: "شکریہ آپ کی مدد کے لیے۔", translation: "Thanks for your help.", tip: "'شکریہ' for thanks + 'کے لیے' (for) are Urdu constructions.", highlights: ["شکریہ", "کے لیے"] },
      { phrase: "پاکستان بہت خوبصورت ہے۔", translation: "Pakistan is very beautiful.", tip: "Persian letter 'پ' + Urdu 'ہ' shapes + '۔' mark Urdu.", highlights: ["پ", "ہے"] },
      { phrase: "میرا نام احمد ہے۔", translation: "My name is Ahmad.", tip: "'میرا نام … ہے' is the classic Urdu self-introduction.", highlights: ["میرا", "ہے"] },
    ],
  },
  {
    lang: "Hebrew",
    aliases: ["עברית", "Ivrit"],
    tag: "he",
    variants: [
      { phrase: "אני לא מדבר עברית טוב.", translation: "I don't speak Hebrew well.", tip: "Right-to-left square letters that don't connect — Hebrew vs. Arabic's cursive.", highlights: ["עברית"] },
      { phrase: "שלום, מה שלומך היום?", translation: "Hello, how are you today?", tip: "'שלום' (shalom) is the iconic Hebrew greeting.", highlights: ["שלום"] },
      { phrase: "הילד קורא ספר.", translation: "The child is reading a book.", tip: "Definite article 'ה-' attaches directly to nouns in Hebrew.", highlights: ["ה"] },
      { phrase: "אני אוהב אותך.", translation: "I love you.", tip: "'אני' (I) and 'אוהב' (love) show Hebrew roots + prefix patterns.", highlights: ["אני", "אוהב"] },
      { phrase: "הילדים משחקים בגן.", translation: "The children are playing in the park.", tip: "Final letters ם (at 'הילדים' end) take a different form — Hebrew orthography.", highlights: ["ם", "ם"] },
      { phrase: "תודה רבה על העזרה.", translation: "Thank you very much for the help.", tip: "'תודה רבה' (thanks very much) is a Hebrew staple.", highlights: ["תודה"] },
      { phrase: "הוא גר בתל אביב.", translation: "He lives in Tel Aviv.", tip: "'הוא' (he) + city 'תל אביב' are Hebrew specifics.", highlights: ["הוא", "תל אביב"] },
      { phrase: "הספר נמצא על השולחן.", translation: "The book is on the table.", tip: "The definite ה- repeats on each definite noun — typical Hebrew.", highlights: ["ה", "ה", "ה"] },
    ],
  },
  {
    lang: "Yiddish",
    aliases: ["ייִדיש"],
    tag: "yi",
    variants: [
      { phrase: "איך רעד נישט קיין גוטן ייִדיש.", translation: "I don't speak good Yiddish.", tip: "Hebrew letters used to write a Germanic language — 'איך'='ikh'='I'.", highlights: ["איך"] },
      { phrase: "ייִדיש איז מײַן מאַמע-לשון.", translation: "Yiddish is my mother tongue.", tip: "Digraphs like ײַ (with pasekh) and אַ (pasekh alef) are Yiddish.", highlights: ["ייִ", "ײַ", "אַ"] },
      { phrase: "אַ גוטן טאָג!", translation: "Good day!", tip: "'אַ' (pasekh alef = 'a') and 'אָ' (komets alef = 'o') distinguish Yiddish from Hebrew.", highlights: ["אַ", "אָ"] },
      { phrase: "איך האָב הונגער.", translation: "I am hungry.", tip: "German-like vocabulary ('האָב' = 'hob' = have) in Hebrew script is Yiddish.", highlights: ["האָב", "אָ"] },
      { phrase: "זיי זענען אין שול.", translation: "They are in (the) synagogue.", tip: "'זענען' (are) and 'שול' (shul) come from German — marks Yiddish.", highlights: ["זענען", "שול"] },
      { phrase: "דער זיידע איז אַ חכם.", translation: "Grandfather is a wise man.", tip: "'דער' (the, masc., like German 'der') + Hebrew-origin 'חכם' shows Yiddish mixing.", highlights: ["דער", "אַ"] },
      { phrase: "וואָס איז דאָס?", translation: "What is that?", tip: "'וואָס' (what) and 'דאָס' (that/neuter) mirror German 'was/das'.", highlights: ["וואָ", "דאָ"] },
      { phrase: "אַ דאַנק פֿאַר דער הילף.", translation: "Thanks for the help.", tip: "'אַ דאַנק' (thanks, from German 'Dank') spelled in Hebrew letters is a Yiddish marker.", highlights: ["דאַנק", "פֿאַר"] },
    ],
  },
  {
    lang: "Hindi",
    aliases: ["हिन्दी"],
    tag: "hi",
    variants: [
      { phrase: "मुझे हिंदी अच्छी तरह नहीं आती।", translation: "I don't know Hindi well.", tip: "Devanagari with a horizontal top bar joining letters, and ending '।'.", highlights: ["।"] },
      { phrase: "नमस्ते, आप कैसे हैं?", translation: "Hello, how are you?", tip: "The iconic 'नमस्ते' greeting plus top bar mark Hindi Devanagari.", highlights: ["नमस्ते"] },
      { phrase: "मेरा नाम राम है।", translation: "My name is Ram.", tip: "Sentence-final 'है।' (is + Devanagari period) is Hindi.", highlights: ["है", "।"] },
      { phrase: "धन्यवाद आपकी मदद के लिए।", translation: "Thank you for your help.", tip: "Conjunct consonants (e.g. 'न्य') with halant are Devanagari.", highlights: ["न्य"] },
      { phrase: "मुझे चाय पीनी है।", translation: "I want to drink tea.", tip: "'मुझे … है' (dative subject + है) is a Hindi construction.", highlights: ["मुझे", "है"] },
      { phrase: "यह किताब बहुत अच्छी है।", translation: "This book is very good.", tip: "'बहुत' (very) + 'अच्छी है' are common Hindi phrasings.", highlights: ["बहुत"] },
      { phrase: "कल मैं दिल्ली जाऊँगा।", translation: "Tomorrow I'll go to Delhi.", tip: "Candrabindu (ँ) nasalisation on 'जाऊँगा' is a Hindi spelling feature.", highlights: ["ँ"] },
      { phrase: "स्कूल घर के पास है।", translation: "The school is near the house.", tip: "Postposition 'के पास' (= 'near') follows the noun in Hindi.", highlights: ["के पास"] },
    ],
  },
  {
    lang: "Bengali",
    aliases: ["Bangla", "বাংলা"],
    tag: "bn",
    variants: [
      { phrase: "আমি ভালো বাংলা জানি না।", translation: "I don't know Bangla well.", tip: "Bangla has a top bar like Devanagari but rounder, curlier letterforms.", highlights: ["বাংলা"] },
      { phrase: "তুমি কেমন আছ?", translation: "How are you?", tip: "'তুমি' (you, informal) + rounded Bangla letters are Bengali.", highlights: ["তুমি"] },
      { phrase: "আমার নাম রাহুল।", translation: "My name is Rahul.", tip: "Bangla sentences also end in '।' (dari), like Hindi.", highlights: ["।"] },
      { phrase: "ধন্যবাদ তোমার সাহায্যের জন্য।", translation: "Thank you for your help.", tip: "Conjunct 'ন্য' and curly 'ধ' are hallmark Bangla shapes.", highlights: ["ধন্যবাদ"] },
      { phrase: "আমি ভাত খাচ্ছি।", translation: "I am eating rice.", tip: "The progressive '-চ্ছি' ending is Bengali.", highlights: ["চ্ছি"] },
      { phrase: "এই বইটি খুব সুন্দর।", translation: "This book is very beautiful.", tip: "Classifier '-টি' attaches to singular nouns in Bengali.", highlights: ["টি"] },
      { phrase: "কলকাতায় অনেক মানুষ।", translation: "There are many people in Kolkata.", tip: "Locative '-য়' ending (kolkata-y) is Bengali case marking.", highlights: ["য়"] },
      { phrase: "রবীন্দ্রনাথ একজন কবি।", translation: "Rabindranath is a poet.", tip: "Cluster 'ন্দ্র' + classifier 'একজন' for persons are Bangla.", highlights: ["ন্দ্র", "একজন"] },
    ],
  },
  {
    lang: "Tamil",
    aliases: ["தமிழ்"],
    tag: "ta",
    variants: [
      { phrase: "எனக்கு தமிழ் நன்றாக தெரியாது.", translation: "I don't know Tamil well.", tip: "Tamil has no top bar (unlike Devanagari/Bangla); loopy, circular letterforms.", highlights: ["தமிழ்"] },
      { phrase: "வணக்கம், எப்படி இருக்கிறீர்கள்?", translation: "Hello, how are you?", tip: "'வணக்கம்' is the Tamil greeting; the pulli dot '்' marks bare consonants.", highlights: ["வணக்கம்", "்"] },
      { phrase: "என் பெயர் முருகன்.", translation: "My name is Murugan.", tip: "'என்' (my) and 'பெயர்' (name) show Tamil's -ன் and -ர் endings.", highlights: ["ன்", "ர்"] },
      { phrase: "நன்றி உங்கள் உதவிக்கு.", translation: "Thanks for your help.", tip: "'நன்றி' for thanks + dative '-க்கு' stack onto nouns.", highlights: ["நன்றி", "க்கு"] },
      { phrase: "நான் சாப்பிடுகிறேன்.", translation: "I am eating.", tip: "Verb ending '-கிறேன்' (present, 1st person) is Tamil.", highlights: ["கிறேன்"] },
      { phrase: "அவன் பள்ளிக்கு போகிறான்.", translation: "He goes to school.", tip: "Retroflex ள் (distinct from l and zha) is Tamil.", highlights: ["ள்", "ான்"] },
      { phrase: "இந்த புத்தகம் நல்லது.", translation: "This book is good.", tip: "'இந்த' (this) + neuter '-து' ending on 'நல்லது' are Tamil.", highlights: ["து"] },
      { phrase: "நாளை நான் சென்னை செல்வேன்.", translation: "Tomorrow I'll go to Chennai.", tip: "Future '-வேன்' verb ending is Tamil grammar.", highlights: ["வேன்"] },
    ],
  },
  {
    lang: "Armenian",
    aliases: ["Հայերեն"],
    tag: "hy",
    variants: [
      { phrase: "Ես լավ հայերեն չեմ խոսում։", translation: "I don't speak Armenian well.", tip: "The unique Armenian alphabet and sentence-ender '։' are unmistakable.", highlights: ["հայերեն", "։"] },
      { phrase: "Բարեւ, ինչպե՞ս ես։", translation: "Hello, how are you?", tip: "The Armenian question mark '՞' sits over a vowel mid-word.", highlights: ["՞", "։"] },
      { phrase: "Իմ անունը Հայկ է։", translation: "My name is Hayk.", tip: "'Է' (is) + sentence-terminator '։' are Armenian.", highlights: ["է", "։"] },
      { phrase: "Շնորհակալություն օգնության համար։", translation: "Thank you for the help.", tip: "'Շնորհակալություն' (thanks) is the distinctly Armenian word.", highlights: ["Շնորհակալություն"] },
      { phrase: "Երեկ եղավ մի շատ լավ օր։", translation: "Yesterday was a very good day.", tip: "The letter 'ը' (schwa) is Armenian; also the -ություն noun ending.", highlights: ["Երեկ", "։"] },
      { phrase: "Ես սիրում եմ քեզ։", translation: "I love you.", tip: "'եմ' (am) + accusative 'քեզ' are Armenian basics.", highlights: ["եմ", "քեզ"] },
      { phrase: "Տղան գնում է դպրոց։", translation: "The boy is going to school.", tip: "'Է' (is/auxiliary) + '-ում' present participle are Armenian grammar.", highlights: ["ում"] },
      { phrase: "Այս գիրքը շատ լավ է։", translation: "This book is very good.", tip: "Definite article '-ը' suffix + 'է' copula mark Armenian.", highlights: ["ը", "է"] },
    ],
  },
  {
    lang: "Georgian",
    aliases: ["ქართული", "Kartuli"],
    tag: "ka",
    variants: [
      { phrase: "ქართული კარგად არ ვიცი.", translation: "I don't know Georgian well.", tip: "Mkhedruli script has no capitals — round, looping letters.", highlights: ["ქართული"] },
      { phrase: "გამარჯობა, როგორ ხარ?", translation: "Hello, how are you?", tip: "'გამარჯობა' (hello) plus Mkhedruli's rounded shapes mark Georgian.", highlights: ["გამარჯობა"] },
      { phrase: "ჩემი სახელი გიორგია.", translation: "My name is Giorgi.", tip: "'ჩემი' (my) + the shape of 'გ' are Georgian.", highlights: ["ჩემი"] },
      { phrase: "გმადლობთ დახმარებისთვის.", translation: "Thank you for the help.", tip: "'გმადლობთ' (thanks) has the consonant cluster gm- typical of Georgian.", highlights: ["გმადლობთ"] },
      { phrase: "წყალი ცივია.", translation: "The water is cold.", tip: "The ejective 'წ' and 'ყ' are Georgian phonemes — nothing else looks like it.", highlights: ["წ", "ყ"] },
      { phrase: "თბილისი ლამაზი ქალაქია.", translation: "Tbilisi is a beautiful city.", tip: "The country's capital name + 'ქალაქი' (city) are Georgian.", highlights: ["თბილისი"] },
      { phrase: "მე ვწერ წერილს.", translation: "I am writing a letter.", tip: "Consonant clusters like 'ვწ' and the 'წ' letter are Georgian.", highlights: ["ვწერ", "წ"] },
      { phrase: "სკოლა სახლთან ახლოს არის.", translation: "The school is near the house.", tip: "Postposition '-თან' (with/near) attaches to the noun.", highlights: ["თან"] },
    ],
  },
  {
    lang: "Amharic",
    aliases: ["አማርኛ"],
    tag: "am",
    variants: [
      { phrase: "አማርኛ በደንብ አልናገርም።", translation: "I don't speak Amharic well.", tip: "Ge'ez/Fidel syllabary — each character is a consonant+vowel syllable block.", highlights: ["አማርኛ"] },
      { phrase: "ሰላም፣ እንዴት ነህ?", translation: "Hello, how are you?", tip: "Ethiopic word separator '፣' (like a Western comma) is distinctive.", highlights: ["፣"] },
      { phrase: "ስሜ ዳዊት ነው።", translation: "My name is Dawit.", tip: "The Ethiopic full stop '።' (nebäb hulätt) ends sentences.", highlights: ["።"] },
      { phrase: "አመሰግናለሁ ስለ እርዳታዎ።", translation: "Thank you for your help.", tip: "'አመሰግናለሁ' (thanks) with stacked syllable glyphs is Amharic.", highlights: ["አመሰግናለሁ"] },
      { phrase: "ውሃ እፈልጋለሁ።", translation: "I want water.", tip: "The verbal ending '-ለሁ' on 'I …' forms is a hallmark of Amharic present tense.", highlights: ["ለሁ"] },
      { phrase: "ቡና ጥሩ ነው።", translation: "The coffee is good.", tip: "'ቡና' = coffee (where the word originated) + 'ነው' (is) are Amharic.", highlights: ["ቡና", "ነው"] },
      { phrase: "ልጁ መጽሐፍ ያነባል።", translation: "The boy is reading a book.", tip: "Definite '-ው/-ጁ' suffix on 'ልጁ' (the boy) + syllable blocks mark Amharic.", highlights: ["ጁ"] },
      { phrase: "አዲስ አበባ ዋና ከተማ ናት።", translation: "Addis Ababa is the capital city.", tip: "Capital's name + '-ናት' feminine 'is' mark Amharic.", highlights: ["አዲስ አበባ", "ናት"] },
    ],
  },
  {
    lang: "Mongolian",
    aliases: ["Монгол"],
    tag: "mn",
    variants: [
      { phrase: "Би монгол хэлээр сайн ярьдаггүй.", translation: "I don't speak Mongolian well.", tip: "Cyrillic with 'ү' — a letter absent from Russian.", highlights: ["ү"] },
      { phrase: "Сайн байна уу?", translation: "Hello, how are you?", tip: "'Сайн байна уу?' is the Mongolian greeting; double 'уу' is typical.", highlights: ["уу"] },
      { phrase: "Миний нэр Болд.", translation: "My name is Bold.", tip: "'Би' (I) with genitive 'Миний' (my) is Mongolian.", highlights: ["Миний"] },
      { phrase: "Баярлалаа тусалсанд.", translation: "Thanks for helping.", tip: "Double-a 'аа' in 'Баярлалаа' + '-санд' dative-locative are Mongolian.", highlights: ["аа", "санд"] },
      { phrase: "Улаанбаатар том хот.", translation: "Ulaanbaatar is a big city.", tip: "Triple-a 'аа' long vowels and 'Улаанбаатар' are Mongolian.", highlights: ["аа", "аа"] },
      { phrase: "Би цай уухыг хүсч байна.", translation: "I want to drink tea.", tip: "Continuous aspect 'байна' and ү/ө vowels mark Mongolian.", highlights: ["ү", "байна"] },
      { phrase: "Өнөөдөр маш хүйтэн байна.", translation: "Today is very cold.", tip: "'Өнөөдөр' (today) starts with the unmistakable Mongolian letter Ө.", highlights: ["Ө", "ө"] },
      { phrase: "Ном ширээн дээр байна.", translation: "The book is on the table.", tip: "Postposition 'дээр' (on) + 'байна' (is) are Mongolian syntax.", highlights: ["дээр", "байна"] },
    ],
  },
  {
    lang: "Zulu",
    aliases: ["isiZulu"],
    tag: "zu",
    variants: [
      { phrase: "Angisikhulumi kahle isiZulu.", translation: "I don't speak Zulu well.", tip: "Language prefix 'isi-' (isiZulu) and negative 'Angi-' are Zulu grammar.", highlights: ["isi", "Angi"] },
      { phrase: "Sawubona, unjani namhlanje?", translation: "Hello, how are you today?", tip: "'Sawubona' is the Zulu greeting; 'hl' digraph is a lateral fricative.", highlights: ["Sawubona", "hl"] },
      { phrase: "Igama lami nginguThemba.", translation: "My name is Themba.", tip: "'nginguThemba' — the whole 'I am Themba' compressed into one word is Nguni/Zulu.", highlights: ["ngi"] },
      { phrase: "Ngiyabonga kakhulu.", translation: "Thank you very much.", tip: "'Ngiyabonga' (I thank) + 'kakhulu' (very much) are classic Zulu.", highlights: ["Ngi", "kh"] },
      { phrase: "Ngcela usizo lwakho.", translation: "Please, your help.", tip: "'Ngc' cluster encodes a dental click — unique to Zulu/Xhosa.", highlights: ["Ngc"] },
      { phrase: "Iqanda libomvu.", translation: "The egg is red.", tip: "The letter 'q' stands for a palatal click consonant.", highlights: ["q"] },
      { phrase: "Uxolo ngephutha lami.", translation: "Sorry for my mistake.", tip: "The letter 'x' stands for a lateral click in Zulu.", highlights: ["x"] },
      { phrase: "Umfundi ufunda incwadi.", translation: "The student is reading a book.", tip: "Concordial agreement: 'u-' subject + 'u-' verb prefix match class — Bantu/Zulu.", highlights: ["U", "u", "nc"] },
    ],
  },
];
