// Language quiz bank. Each entry has:
//   lang      - canonical language name (shown after guess)
//   aliases   - other acceptable names the user might type
//   phrase    - sentence/phrase in the language's native script
//   translation - English translation
//   tip       - how to quickly tell this language apart
//   tag       - BCP-47 lang tag for font rendering hints
const QUESTIONS = [
  {
    lang: "Spanish",
    aliases: ["Español", "Castellano", "Castilian"],
    phrase: "¿Dónde está la biblioteca más cercana?",
    translation: "Where is the nearest library?",
    tip: "The inverted ¿ and ¡ at the start of questions/exclamations are unique to Spanish. Also watch for ñ and words ending in -ción.",
    tag: "es",
  },
  {
    lang: "French",
    aliases: ["Français"],
    phrase: "Je ne sais pas ce que tu veux dire.",
    translation: "I don't know what you mean.",
    tip: "Look for ç, the circumflex (â ê î ô û), lots of apostrophes (l', d', qu'), and the 'ne … pas' sandwich around the verb.",
    tag: "fr",
  },
  {
    lang: "German",
    aliases: ["Deutsch"],
    phrase: "Ich kann leider kein Wort verstehen.",
    translation: "Unfortunately I can't understand a word.",
    tip: "The ß (eszett) is a dead giveaway, as are umlauts (ä ö ü) and the habit of Capitalising Every Noun mid-sentence.",
    tag: "de",
  },
  {
    lang: "Italian",
    aliases: ["Italiano"],
    phrase: "La pizza è davvero buonissima stasera.",
    translation: "The pizza is really excellent tonight.",
    tip: "Almost every word ends in a vowel. Look for doubled consonants (zz, tt, ss), 'gli', 'gn', and è with a grave accent.",
    tag: "it",
  },
  {
    lang: "Portuguese",
    aliases: ["Português"],
    phrase: "Não sei o que você está dizendo agora.",
    translation: "I don't know what you're saying right now.",
    tip: "Nasal vowels ã and õ (plus -ão endings like 'não', 'coração') are the signature — nothing else in Europe writes them.",
    tag: "pt",
  },
  {
    lang: "Dutch",
    aliases: ["Nederlands", "Flemish"],
    phrase: "Ik spreek een klein beetje Nederlands.",
    translation: "I speak a little bit of Dutch.",
    tip: "The 'ij' digraph (tied together or written IJ capitalised) plus doubled vowels (aa, ee, oo) and 'sch' clusters scream Dutch.",
    tag: "nl",
  },
  {
    lang: "Swedish",
    aliases: ["Svenska"],
    phrase: "Jag pratar inte svenska särskilt bra.",
    translation: "I don't speak Swedish particularly well.",
    tip: "Swedish uses å, ä, ö (never æ or ø). 'Jag', 'och', and 'är' are everywhere.",
    tag: "sv",
  },
  {
    lang: "Norwegian",
    aliases: ["Norsk", "Bokmål", "Nynorsk"],
    phrase: "Jeg snakker bare litt norsk.",
    translation: "I only speak a little Norwegian.",
    tip: "Norwegian uses æ, ø, å (like Danish). Tell it from Danish by softer spellings — 'jeg snakker' vs Danish 'jeg taler'.",
    tag: "no",
  },
  {
    lang: "Danish",
    aliases: ["Dansk"],
    phrase: "Jeg taler kun lidt dansk, desværre.",
    translation: "I only speak a little Danish, unfortunately.",
    tip: "Shares æ, ø, å with Norwegian. 'Taler' (not 'snakker') and the -kke endings ('ikke') lean Danish.",
    tag: "da",
  },
  {
    lang: "Finnish",
    aliases: ["Suomi"],
    phrase: "En puhu suomea kovin hyvin.",
    translation: "I don't speak Finnish very well.",
    tip: "Long strings of vowels (uu, ää, yy) and doubled consonants (kk, tt), no articles, and ä/ö but NEVER å.",
    tag: "fi",
  },
  {
    lang: "Icelandic",
    aliases: ["Íslenska"],
    phrase: "Ég tala smá íslensku.",
    translation: "I speak a little Icelandic.",
    tip: "The letters ð (eth) and þ (thorn) are found almost nowhere else — an instant tell for Icelandic.",
    tag: "is",
  },
  {
    lang: "Polish",
    aliases: ["Polski"],
    phrase: "Nie rozumiem, co mówisz do mnie.",
    translation: "I don't understand what you're saying to me.",
    tip: "Barrelling consonant clusters (sz, cz, rz, szcz) plus the slashed ł and hook letters ą, ę are classic Polish.",
    tag: "pl",
  },
  {
    lang: "Czech",
    aliases: ["Čeština"],
    phrase: "Nerozumím, co mi říkáš.",
    translation: "I don't understand what you're telling me.",
    tip: "Háček marks (č, š, ž, ř, ě) and the ring-u (ů) are Czech hallmarks. The letter ř is essentially unique to Czech.",
    tag: "cs",
  },
  {
    lang: "Slovak",
    aliases: ["Slovenčina", "Slovenský"],
    phrase: "Nerozumiem, čo mi hovoríš.",
    translation: "I don't understand what you're telling me.",
    tip: "Looks like Czech, but Slovak has ľ, ĺ, ŕ, and ô — and never uses ř.",
    tag: "sk",
  },
  {
    lang: "Hungarian",
    aliases: ["Magyar"],
    phrase: "Nem értem, amit éppen mondasz.",
    translation: "I don't understand what you're saying right now.",
    tip: "The 'double-acute' letters ő and ű exist only in Hungarian. Long compound words and digraphs (sz, zs, cs, gy, ny, ty) also give it away.",
    tag: "hu",
  },
  {
    lang: "Romanian",
    aliases: ["Română", "Romanian"],
    phrase: "Nu înțeleg ce îmi spui acum.",
    translation: "I don't understand what you're telling me now.",
    tip: "Romanian is the only Romance language with ă, â, î and comma-below ș, ț. 'Nu', 'și', 'este' are common.",
    tag: "ro",
  },
  {
    lang: "Turkish",
    aliases: ["Türkçe"],
    phrase: "Biraz Türkçe konuşuyorum.",
    translation: "I speak a little Turkish.",
    tip: "The dotless ı vs dotted i (and ğ — always silent) are Turkish signatures. Long agglutinated words like 'konuşuyorum' too.",
    tag: "tr",
  },
  {
    lang: "Greek",
    aliases: ["Ελληνικά", "Hellenic"],
    phrase: "Δεν καταλαβαίνω τι λες.",
    translation: "I don't understand what you're saying.",
    tip: "The Greek alphabet (Δ, Λ, Ω, ψ, φ, θ…) is unmistakable once you see it.",
    tag: "el",
  },
  {
    lang: "Russian",
    aliases: ["Русский"],
    phrase: "Я плохо говорю по-русски.",
    translation: "I don't speak Russian well.",
    tip: "Cyrillic + the letters ы, э, ъ, ё point to Russian. No і, ї, є (those are Ukrainian).",
    tag: "ru",
  },
  {
    lang: "Ukrainian",
    aliases: ["Українська"],
    phrase: "Я погано розмовляю українською.",
    translation: "I don't speak Ukrainian well.",
    tip: "Cyrillic with і, ї, є, and ґ — none of which exist in Russian. Also apostrophes: м'я.",
    tag: "uk",
  },
  {
    lang: "Bulgarian",
    aliases: ["Български"],
    phrase: "Не разбирам какво казваш.",
    translation: "I don't understand what you're saying.",
    tip: "Cyrillic, but Bulgarian uses ъ as a normal vowel mid-word ('България'), which stands out.",
    tag: "bg",
  },
  {
    lang: "Serbian",
    aliases: ["Српски", "Srpski"],
    phrase: "Не разумем шта говориш.",
    translation: "I don't understand what you're saying.",
    tip: "Cyrillic with љ, њ, ћ, ђ, џ — letters that don't appear in Russian. Serbian also has a Latin form (š, č, ć, đ, ž).",
    tag: "sr",
  },
  {
    lang: "Croatian",
    aliases: ["Hrvatski"],
    phrase: "Ne razumijem što govoriš.",
    translation: "I don't understand what you're saying.",
    tip: "Latin alphabet with č, ć, š, ž, đ. Uses 'što'/'što' or 'što'; compare Serbian Cyrillic or 'šta'.",
    tag: "hr",
  },
  {
    lang: "Slovenian",
    aliases: ["Slovenščina"],
    phrase: "Ne razumem, kaj praviš.",
    translation: "I don't understand what you're saying.",
    tip: "Only č, š, ž as special letters — no ć, đ (those mean Croatian/Serbian). 'Kaj' and dual-number verbs are typical.",
    tag: "sl",
  },
  {
    lang: "Albanian",
    aliases: ["Shqip"],
    phrase: "Nuk flas mirë shqip.",
    translation: "I don't speak Albanian well.",
    tip: "The schwa ë is everywhere, plus digraphs xh, gj, nj, sh, th, dh. 'Nuk' means 'not'.",
    tag: "sq",
  },
  {
    lang: "Lithuanian",
    aliases: ["Lietuvių"],
    phrase: "Nemoku gerai kalbėti lietuviškai.",
    translation: "I don't speak Lithuanian well.",
    tip: "Archaic-looking endings in -as, -is, -us, plus ogonek letters ą, ę, į, ų and dot-above ė.",
    tag: "lt",
  },
  {
    lang: "Latvian",
    aliases: ["Latviešu"],
    phrase: "Es nerunāju latviski labi.",
    translation: "I don't speak Latvian well.",
    tip: "Macron vowels ā, ē, ī, ū plus cedilla-like hooks on ģ, ķ, ļ, ņ are distinctly Latvian.",
    tag: "lv",
  },
  {
    lang: "Estonian",
    aliases: ["Eesti"],
    phrase: "Ma ei oska hästi eesti keelt.",
    translation: "I don't speak Estonian well.",
    tip: "Estonian uses õ (same letter Portuguese uses) alongside ä, ö, ü — but no å. Lots of double vowels like Finnish.",
    tag: "et",
  },
  {
    lang: "Catalan",
    aliases: ["Català"],
    phrase: "No parlo gaire bé el català.",
    translation: "I don't speak Catalan very well.",
    tip: "The 'l·l' with a middle dot is uniquely Catalan. Mix of Spanish-ish and French-ish vocabulary, plus ç.",
    tag: "ca",
  },
  {
    lang: "Galician",
    aliases: ["Galego"],
    phrase: "Non falo moi ben galego.",
    translation: "I don't speak Galician well.",
    tip: "Looks like Portuguese but uses ñ (from Spanish). 'Non' for 'no', 'x' for the 'sh' sound as in 'Xunta'.",
    tag: "gl",
  },
  {
    lang: "Basque",
    aliases: ["Euskara"],
    phrase: "Ez dakit euskaraz ondo hitz egiten.",
    translation: "I don't know how to speak Basque well.",
    tip: "Basque is unrelated to any neighbour. Loads of k, tx, tz, x, and 'ez' for 'no'. Words like 'euskara' and 'kaixo' are giveaways.",
    tag: "eu",
  },
  {
    lang: "Welsh",
    aliases: ["Cymraeg"],
    phrase: "Dwi ddim yn siarad Cymraeg yn dda.",
    translation: "I don't speak Welsh well.",
    tip: "Double-letter consonants (ll, dd, ff, rh) and 'w' and 'y' acting as vowels ('cwm', 'cymru') mark Welsh.",
    tag: "cy",
  },
  {
    lang: "Irish",
    aliases: ["Gaeilge", "Irish Gaelic"],
    phrase: "Níl Gaeilge mhaith agam.",
    translation: "I don't have good Irish.",
    tip: "Acute-accent vowels (á é í ó ú — the 'síneadh fada') plus silent-letter clusters bh, mh, dh, gh are Irish.",
    tag: "ga",
  },
  {
    lang: "Scottish Gaelic",
    aliases: ["Gàidhlig", "Scots Gaelic"],
    phrase: "Chan eil Gàidhlig mhath agam.",
    translation: "I don't have good Gaelic.",
    tip: "Like Irish, but uses the GRAVE accent (à, è, ì, ò, ù) instead of acute. 'Chan eil' for 'is not'.",
    tag: "gd",
  },
  {
    lang: "Latin",
    aliases: ["Lingua Latina"],
    phrase: "Latine non bene loquor.",
    translation: "I don't speak Latin well.",
    tip: "No accents, no diacritics, and classic case endings like -us, -um, -is, -orum. No 'j', 'w', or 'v'-vs-'u' distinction in classical form.",
    tag: "la",
  },
  {
    lang: "Esperanto",
    aliases: [],
    phrase: "Mi ne parolas Esperanton tre bone.",
    translation: "I don't speak Esperanto very well.",
    tip: "The circumflex letters ĉ, ĝ, ĥ, ĵ, ŝ and breve ŭ are uniquely Esperanto. Nouns end -o, adjectives -a, accusative adds -n.",
    tag: "eo",
  },
  {
    lang: "Afrikaans",
    aliases: [],
    phrase: "Ek praat nie baie goed Afrikaans nie.",
    translation: "I don't speak Afrikaans very well.",
    tip: "Reads like simplified Dutch, with 'nie … nie' double negation and 'ek' for 'I'. No doubled vowels you'd see in Dutch.",
    tag: "af",
  },
  {
    lang: "Swahili",
    aliases: ["Kiswahili"],
    phrase: "Sisemi Kiswahili vizuri sana.",
    translation: "I don't speak Swahili very well.",
    tip: "Noun-class prefixes (ki-, m-, wa-, ma-) and lots of -a/-i/-u endings. Latin script, no tones, no diacritics.",
    tag: "sw",
  },
  {
    lang: "Indonesian",
    aliases: ["Bahasa Indonesia", "Malay", "Bahasa Melayu"],
    phrase: "Saya tidak bisa berbahasa Indonesia dengan baik.",
    translation: "I can't speak Indonesian well.",
    tip: "Latin, no tones, no diacritics. Reduplication ('orang-orang') and prefixes ber-/men-/ter- are the signature.",
    tag: "id",
  },
  {
    lang: "Tagalog",
    aliases: ["Filipino"],
    phrase: "Hindi ako magaling magsalita ng Tagalog.",
    translation: "I'm not good at speaking Tagalog.",
    tip: "The ng digraph as a word ('ng', 'mga'), plus 'hindi' meaning 'no/not', mark Tagalog.",
    tag: "tl",
  },
  {
    lang: "Vietnamese",
    aliases: ["Tiếng Việt"],
    phrase: "Tôi không nói tiếng Việt giỏi.",
    translation: "I don't speak Vietnamese well.",
    tip: "Latin alphabet loaded with stacked tone marks (à, á, ả, ã, ạ) and the barred đ. Monosyllabic words.",
    tag: "vi",
  },
  {
    lang: "Korean",
    aliases: ["한국어", "Hangugeo"],
    phrase: "저는 한국어를 잘 못해요.",
    translation: "I don't speak Korean well.",
    tip: "Hangul syllable blocks built from circles, lines and squares (ㅇ ㅁ ㄱ). No Chinese characters in modern writing.",
    tag: "ko",
  },
  {
    lang: "Japanese",
    aliases: ["日本語", "Nihongo"],
    phrase: "日本語があまり上手ではありません。",
    translation: "I'm not very good at Japanese.",
    tip: "A mix of three scripts: kanji (Chinese-looking), hiragana (curvy: あ, の, を) and katakana (angular: カ, タ). That mix = Japanese.",
    tag: "ja",
  },
  {
    lang: "Chinese",
    aliases: ["Mandarin", "中文", "普通话", "Putonghua", "Simplified Chinese", "Traditional Chinese"],
    phrase: "我不太会说中文。",
    translation: "I can't speak Chinese very well.",
    tip: "Solid block of Hanzi characters with no phonetic script mixed in, and no spaces — unlike Japanese which mixes scripts.",
    tag: "zh",
  },
  {
    lang: "Thai",
    aliases: ["ภาษาไทย"],
    phrase: "ฉันพูดภาษาไทยไม่เก่ง",
    translation: "I don't speak Thai well.",
    tip: "Thai script has tall loops and hooks above the letters, no spaces between words, and tone marks over vowels.",
    tag: "th",
  },
  {
    lang: "Khmer",
    aliases: ["Cambodian", "ភាសាខ្មែរ"],
    phrase: "ខ្ញុំមិនចេះភាសាខ្មែរទេ។",
    translation: "I don't know Khmer.",
    tip: "Dense, curly script with stacked subscript consonants (little glyphs hanging below the line). No spaces between words.",
    tag: "km",
  },
  {
    lang: "Arabic",
    aliases: ["العربية"],
    phrase: "أنا لا أتكلم العربية جيداً.",
    translation: "I don't speak Arabic well.",
    tip: "Right-to-left cursive script where letters connect. No letters p, v, or g — compare Persian/Urdu which add those.",
    tag: "ar",
  },
  {
    lang: "Persian",
    aliases: ["Farsi", "فارسی"],
    phrase: "من فارسی را خوب صحبت نمی‌کنم.",
    translation: "I don't speak Persian well.",
    tip: "Arabic script plus four extra letters — پ, چ, ژ, گ — that Arabic doesn't have. Common words: 'من' (I), 'است' (is).",
    tag: "fa",
  },
  {
    lang: "Urdu",
    aliases: ["اردو"],
    phrase: "مجھے اردو اچھی طرح نہیں آتی۔",
    translation: "I don't know Urdu well.",
    tip: "Uses the flowing Nastaliq style of the Perso-Arabic script — lines slope down from right to left, unlike Arabic's level baseline.",
    tag: "ur",
  },
  {
    lang: "Hebrew",
    aliases: ["עברית", "Ivrit"],
    phrase: "אני לא מדבר עברית טוב.",
    translation: "I don't speak Hebrew well.",
    tip: "Right-to-left square-shaped letters that don't connect, no curves like Arabic, and usually no vowel marks shown.",
    tag: "he",
  },
  {
    lang: "Yiddish",
    aliases: ["ייִדיש"],
    phrase: "איך רעד נישט קיין גוטן ייִדיש.",
    translation: "I don't speak good Yiddish.",
    tip: "Hebrew letters used for a Germanic language — you may recognise German-looking words spelled in Hebrew script ('איך'='ikh'='I').",
    tag: "yi",
  },
  {
    lang: "Hindi",
    aliases: ["हिन्दी"],
    phrase: "मुझे हिंदी अच्छी तरह नहीं आती।",
    translation: "I don't know Hindi well.",
    tip: "Devanagari script — a horizontal bar connects the letters across the top of each word. Sentence-ender '।' instead of a period.",
    tag: "hi",
  },
  {
    lang: "Bengali",
    aliases: ["Bangla", "বাংলা"],
    phrase: "আমি ভালো বাংলা জানি না।",
    translation: "I don't know Bangla well.",
    tip: "Looks like Devanagari with a top bar, but letters are curlier and rounder. Distinct 'ব' and 'ক' shapes.",
    tag: "bn",
  },
  {
    lang: "Tamil",
    aliases: ["தமிழ்"],
    phrase: "எனக்கு தமிழ் நன்றாக தெரியாது.",
    translation: "I don't know Tamil well.",
    tip: "No top horizontal bar (unlike Hindi/Bengali). Loops and curls, and famously few consonants — lots of 'ன', 'ந', 'ம', 'ள'.",
    tag: "ta",
  },
  {
    lang: "Armenian",
    aliases: ["Հայերեն"],
    phrase: "Ես լավ հայերեն չեմ խոսում։",
    translation: "I don't speak Armenian well.",
    tip: "A unique alphabet that looks a bit like Greek crossed with Latin. Sentences end with '։' (a double-dot).",
    tag: "hy",
  },
  {
    lang: "Georgian",
    aliases: ["ქართული", "Kartuli"],
    phrase: "ქართული კარგად არ ვიცი.",
    translation: "I don't know Georgian well.",
    tip: "Mkhedruli script — rounded, looping letters with no capitals at all. Looks like nothing else on earth.",
    tag: "ka",
  },
  {
    lang: "Amharic",
    aliases: ["አማርኛ"],
    phrase: "አማርኛ በደንብ አልናገርም።",
    translation: "I don't speak Amharic well.",
    tip: "Ge'ez/Fidel script — each character is a consonant+vowel syllable block. Sentence ender '።' is also characteristic.",
    tag: "am",
  },
  {
    lang: "Mongolian",
    aliases: ["Монгол"],
    phrase: "Би монгол хэлээр сайн ярьдаггүй.",
    translation: "I don't speak Mongolian well.",
    tip: "Cyrillic, but uses ө and ү (like Turkish's ö and ü) which aren't in Russian. 'Би' = 'I'.",
    tag: "mn",
  },
  {
    lang: "Zulu",
    aliases: ["isiZulu"],
    phrase: "Angisikhulumi kahle isiZulu.",
    translation: "I don't speak Zulu well.",
    tip: "Latin alphabet with 'ngq', 'nkc', 'hl', 'dl' clusters — the 'c', 'q', 'x' letters stand for click consonants.",
    tag: "zu",
  },
];
